-- Enable required extensions
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";
CREATE EXTENSION IF NOT EXISTS "pgcrypto";
CREATE EXTENSION IF NOT EXISTS "pg_trgm"; -- For text search (products)

-- 1. Users Table (Replaces Supabase auth.users)
CREATE TABLE IF NOT EXISTS users (
  id UUID DEFAULT uuid_generate_v4() PRIMARY KEY,
  email TEXT NOT NULL UNIQUE,
  password_hash TEXT,
  full_name TEXT,
  phone TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 2. Email OTP Codes
CREATE TABLE IF NOT EXISTS email_otp_codes (
  id UUID DEFAULT uuid_generate_v4() PRIMARY KEY,
  email TEXT NOT NULL,
  code TEXT NOT NULL,
  expires_at TIMESTAMP WITH TIME ZONE NOT NULL,
  used BOOLEAN DEFAULT FALSE,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_email_otp_email_created_at ON email_otp_codes(email, created_at DESC);

-- 3. WhatsApp Sessions (Managed by WAHA)
CREATE TABLE IF NOT EXISTS whatsapp_sessions (
  id UUID DEFAULT uuid_generate_v4() PRIMARY KEY,
  session_id TEXT NOT NULL UNIQUE,
  session_name TEXT UNIQUE,
  user_email TEXT,
  user_id UUID REFERENCES users(id), -- Changed to UUID and FK
  plan_days INT,
  qr_code TEXT,
  status TEXT DEFAULT 'stopped',
  qr TEXT,
  expires_at TIMESTAMP WITH TIME ZONE,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 4. User Configurations
CREATE TABLE IF NOT EXISTS user_configs (
  id UUID DEFAULT uuid_generate_v4() PRIMARY KEY,
  user_id UUID UNIQUE REFERENCES users(id), -- Changed to UUID and FK
  ai_provider TEXT DEFAULT 'openrouter', -- 'openai', 'gemini', 'openrouter', 'groq'
  api_key TEXT,
  model_name TEXT DEFAULT 'openrouter/auto',
  system_prompt TEXT,
  auto_reply BOOLEAN DEFAULT TRUE,
  ai_enabled BOOLEAN DEFAULT TRUE,
  media_enabled BOOLEAN DEFAULT TRUE,
  response_language TEXT DEFAULT 'bn',
  balance NUMERIC DEFAULT 0,
  message_credit NUMERIC DEFAULT 0,
  response_tone TEXT,
  service_api_key TEXT UNIQUE,
  email TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_user_configs_email ON user_configs(email);

-- 5. WPP Debounce
CREATE TABLE IF NOT EXISTS wpp_debounce (
  id UUID DEFAULT uuid_generate_v4() PRIMARY KEY,
  debounce_key TEXT NOT NULL UNIQUE, -- e.g., 'pageId_senderId'
  last_message_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  is_processing BOOLEAN DEFAULT FALSE
);
CREATE INDEX IF NOT EXISTS idx_wpp_debounce_key ON wpp_debounce(debounce_key);

-- 6. WP Chats
CREATE TABLE IF NOT EXISTS wp_chats (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  page_id TEXT,
  sender_id TEXT,
  text TEXT,
  status TEXT,
  timestamp BIGINT,
  media_type TEXT DEFAULT 'text', -- 'text', 'image', 'audio'
  media_url TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_wp_chats_sender_page_status ON wp_chats(sender_id, page_id, status);

-- 7. Session QR Link
CREATE TABLE IF NOT EXISTS session_qr_link ( 
   id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY, 
   qr_link TEXT NOT NULL, 
   session_name TEXT, 
   session_used BOOLEAN DEFAULT FALSE
);

-- 8. WhatsApp Message Database
CREATE TABLE IF NOT EXISTS whatsapp_message_database (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  session_name TEXT NOT NULL UNIQUE,
  user_id UUID REFERENCES users(id), -- Changed to UUID and FK
  email TEXT,
  active BOOLEAN DEFAULT TRUE,
  status TEXT DEFAULT 'created',
  reply_message BOOLEAN DEFAULT FALSE,
  swipe_reply BOOLEAN DEFAULT FALSE,
  order_tracking BOOLEAN DEFAULT FALSE,
  image_detection BOOLEAN DEFAULT FALSE,
  image_send BOOLEAN DEFAULT FALSE,
  audio_detection BOOLEAN DEFAULT FALSE,
  file_upload BOOLEAN DEFAULT FALSE,
  group_reply BOOLEAN DEFAULT FALSE,
  text_prompt TEXT,
  subscription_status TEXT DEFAULT 'active',
  expires_at TIMESTAMP WITH TIME ZONE,
  plan_days INTEGER DEFAULT 30,
  qr_code TEXT,
  api_key TEXT,
  cheap_engine BOOLEAN DEFAULT TRUE,
  block_emoji TEXT,
  unblock_emoji TEXT,
  lock_emojis TEXT,
  unlock_emojis TEXT,
  check_conversion INTEGER DEFAULT 20,
  image_prompt TEXT,
  memory_context_name TEXT,
  order_lock_minutes INTEGER DEFAULT 1440,
  wait_time INTEGER,
  emoji_check_count INTEGER DEFAULT 50
);

-- 9. WhatsApp Chats
CREATE TABLE IF NOT EXISTS whatsapp_chats (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  session_name TEXT NOT NULL,
  sender_id TEXT NOT NULL,
  recipient_id TEXT,
  message_id TEXT NOT NULL UNIQUE,
  text TEXT,
  timestamp BIGINT,
  status TEXT,
  reply_by TEXT,
  token_usage INTEGER DEFAULT 0,
  is_group BOOLEAN DEFAULT FALSE,
  group_id TEXT,
  group_name TEXT,
  model_used TEXT
);
CREATE INDEX IF NOT EXISTS idx_whatsapp_chats_session_sender ON whatsapp_chats(session_name, sender_id);
CREATE INDEX IF NOT EXISTS idx_whatsapp_chats_timestamp ON whatsapp_chats(timestamp DESC);

-- 10. Facebook Page Integration
CREATE TABLE IF NOT EXISTS page_access_token_message (
  page_id TEXT PRIMARY KEY,
  name TEXT,
  page_access_token TEXT,
  data_sheet TEXT,
  secret_key TEXT,
  found_id TEXT,
  email TEXT,
  ai TEXT DEFAULT 'openrouter',
  api_key TEXT,
  chat_model TEXT DEFAULT 'openrouter/auto',
  subscription_status TEXT DEFAULT 'inactive', -- active, inactive, trial
  subscription_plan TEXT,
  subscription_expiry TIMESTAMP WITH TIME ZONE,
  message_credit NUMERIC DEFAULT 0,
  cheap_engine BOOLEAN DEFAULT TRUE,
  user_access_token TEXT,
  user_id UUID REFERENCES users(id), -- Changed to UUID and FK
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 11. FB Message Database
CREATE TABLE IF NOT EXISTS fb_message_database (
  id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  page_id TEXT NOT NULL,
  text_prompt TEXT,
  reply_message BOOLEAN DEFAULT TRUE,
  swipe_reply BOOLEAN DEFAULT TRUE,
  image_detection BOOLEAN DEFAULT FALSE,
  image_send BOOLEAN DEFAULT FALSE,
  template BOOLEAN DEFAULT FALSE,
  order_tracking BOOLEAN DEFAULT FALSE,
  image_prompt TEXT,
  template_prompt_x1 TEXT,
  template_prompt_x2 TEXT,
  verified BOOLEAN DEFAULT TRUE,
  wait INTEGER DEFAULT 8,
  block_emoji TEXT,
  unblock_emoji TEXT,
  check_conversion INTEGER DEFAULT 20,
  memory_context_name TEXT,
  order_lock_minutes INTEGER DEFAULT 1440,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 12. Page Prompts
CREATE TABLE IF NOT EXISTS page_prompts (
  page_id TEXT PRIMARY KEY,
  image_prompt TEXT,
  vision_prompt TEXT,
  block_emoji TEXT,
  lock_emojis TEXT,
  unblock_emoji TEXT,
  unlock_emojis TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 13. N8N Chat Histories (Legacy/Alternative)
CREATE TABLE IF NOT EXISTS n8n_chat_histories (
  id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  session_id TEXT NOT NULL, -- Format: page_id_sender_id
  message JSONB NOT NULL, -- Stores { role: 'user'|'assistant', content: '...' }
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_n8n_chat_histories_session ON n8n_chat_histories(session_id);

-- 14. Backend Chat Histories
CREATE TABLE IF NOT EXISTS backend_chat_histories (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  session_id TEXT,
  message JSONB,
  page_id TEXT,
  sender_id TEXT,
  recipient_id TEXT,
  message_id TEXT,
  text TEXT,
  reply_to TEXT,
  image TEXT,
  timestamp BIGINT,
  status TEXT,
  reply_by TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Ensure columns exist (for migration)
DO $$ 
BEGIN 
    BEGIN
        ALTER TABLE backend_chat_histories ADD COLUMN message_id TEXT;
    EXCEPTION
        WHEN duplicate_column THEN RAISE NOTICE 'column message_id already exists in backend_chat_histories.';
    END;
    BEGIN
        ALTER TABLE backend_chat_histories ADD COLUMN page_id TEXT;
    EXCEPTION
        WHEN duplicate_column THEN RAISE NOTICE 'column page_id already exists in backend_chat_histories.';
    END;
    BEGIN
        ALTER TABLE backend_chat_histories ADD COLUMN sender_id TEXT;
    EXCEPTION
        WHEN duplicate_column THEN RAISE NOTICE 'column sender_id already exists in backend_chat_histories.';
    END;
    BEGIN
        ALTER TABLE backend_chat_histories ADD COLUMN recipient_id TEXT;
    EXCEPTION
        WHEN duplicate_column THEN RAISE NOTICE 'column recipient_id already exists in backend_chat_histories.';
    END;
    BEGIN
        ALTER TABLE backend_chat_histories ADD COLUMN text TEXT;
    EXCEPTION
        WHEN duplicate_column THEN RAISE NOTICE 'column text already exists in backend_chat_histories.';
    END;
    BEGIN
        ALTER TABLE backend_chat_histories ADD COLUMN reply_to TEXT;
    EXCEPTION
        WHEN duplicate_column THEN RAISE NOTICE 'column reply_to already exists in backend_chat_histories.';
    END;
    BEGIN
        ALTER TABLE backend_chat_histories ADD COLUMN image TEXT;
    EXCEPTION
        WHEN duplicate_column THEN RAISE NOTICE 'column image already exists in backend_chat_histories.';
    END;
    BEGIN
        ALTER TABLE backend_chat_histories ADD COLUMN timestamp BIGINT;
    EXCEPTION
        WHEN duplicate_column THEN RAISE NOTICE 'column timestamp already exists in backend_chat_histories.';
    END;
    BEGIN
        ALTER TABLE backend_chat_histories ADD COLUMN status TEXT;
    EXCEPTION
        WHEN duplicate_column THEN RAISE NOTICE 'column status already exists in backend_chat_histories.';
    END;
    BEGIN
        ALTER TABLE backend_chat_histories ADD COLUMN reply_by TEXT;
    EXCEPTION
        WHEN duplicate_column THEN RAISE NOTICE 'column reply_by already exists in backend_chat_histories.';
    END;
END $$;

CREATE INDEX IF NOT EXISTS idx_backend_chat_histories_session_id ON backend_chat_histories(session_id);
CREATE INDEX IF NOT EXISTS idx_backend_chat_histories_message_id ON backend_chat_histories(message_id);

-- 15. Label Actions
CREATE TABLE IF NOT EXISTS label_actions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  page_id TEXT NOT NULL,
  label_name TEXT NOT NULL,
  ai_action TEXT DEFAULT 'continue',
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, NOW()),
  UNIQUE(page_id, label_name)
);

-- 16. FB Chats
CREATE TABLE IF NOT EXISTS fb_chats (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  page_id TEXT,
  sender_id TEXT,
  recipient_id TEXT,
  message_id TEXT UNIQUE,
  text TEXT,
  timestamp BIGINT,
  status VARCHAR DEFAULT 'pending',
  reply_by TEXT,
  ai_model TEXT,
  token INTEGER DEFAULT 0,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 17. FB Included Users
CREATE TABLE IF NOT EXISTS fb_included_users (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  page_id TEXT NOT NULL,
  sender_id TEXT,
  key TEXT UNIQUE NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 18. FB Order Tracking
CREATE TABLE IF NOT EXISTS fb_order_tracking (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  page_id TEXT,
  sender_id TEXT,
  product_name TEXT,
  number TEXT,
  location TEXT,
  product_quantity TEXT,
  price TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_fb_order_tracking_page_id ON fb_order_tracking(page_id);

-- 19. WhatsApp Order Tracking
CREATE TABLE IF NOT EXISTS whatsapp_order_tracking (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  session_name TEXT NOT NULL,
  sender_id TEXT,
  product_name TEXT,
  number TEXT,
  location TEXT,
  product_quantity TEXT,
  price TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 20. OpenRouter Engine Config (For Admin)
CREATE TABLE IF NOT EXISTS openrouter_engine_config (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID REFERENCES users(id),
  api_key TEXT,
  model_name TEXT DEFAULT 'google/gemini-2.0-flash-exp:free',
  max_tokens INTEGER DEFAULT 1000,
  temperature NUMERIC DEFAULT 0.7,
  system_prompt TEXT,
  is_active BOOLEAN DEFAULT TRUE,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 21. OpenRouter Engine Keys (Pool)
CREATE TABLE IF NOT EXISTS openrouter_engine_keys (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  key_name TEXT,
  api_key TEXT UNIQUE NOT NULL,
  usage_count INTEGER DEFAULT 0,
  is_active BOOLEAN DEFAULT TRUE,
  last_used TIMESTAMP WITH TIME ZONE,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 22. AI Usage Logs
CREATE TABLE IF NOT EXISTS ai_usage_logs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID REFERENCES users(id),
  session_id TEXT,
  provider TEXT,
  model TEXT,
  tokens_input INTEGER,
  tokens_output INTEGER,
  cost NUMERIC,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 23. Admin Settings
CREATE TABLE IF NOT EXISTS admin_settings (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  key TEXT UNIQUE NOT NULL,
  value TEXT,
  description TEXT,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 24. Referral Codes
CREATE TABLE IF NOT EXISTS referral_codes (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  code TEXT NOT NULL UNIQUE,
  type TEXT DEFAULT 'balance',
  value NUMERIC NOT NULL,
  status TEXT DEFAULT 'active',
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 25. Team Members (NEW)
CREATE TABLE IF NOT EXISTS team_members (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  owner_email TEXT NOT NULL,
  member_email TEXT NOT NULL,
  status TEXT DEFAULT 'pending', -- pending, active, inactive
  role TEXT DEFAULT 'member',
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  UNIQUE(owner_email, member_email)
);

-- 26. Products (NEW)
CREATE TABLE IF NOT EXISTS products (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID REFERENCES users(id),
  name TEXT NOT NULL,
  description TEXT,
  image_url TEXT,
  reply_url TEXT,
  variants JSONB,
  is_active BOOLEAN DEFAULT TRUE,
  price NUMERIC DEFAULT 0,
  currency TEXT DEFAULT 'USD',
  stock INTEGER DEFAULT 0,
  allowed_page_ids JSONB, -- Storing as JSON array of strings
  keywords TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_products_user_id ON products(user_id);

-- 27. Payment Transactions (NEW)
CREATE TABLE IF NOT EXISTS payment_transactions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_email TEXT,
  amount NUMERIC,
  method TEXT,
  trx_id TEXT,
  sender_number TEXT,
  status TEXT DEFAULT 'pending',
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 28. WhatsApp Contacts (NEW)
CREATE TABLE IF NOT EXISTS whatsapp_contacts (
  session_name TEXT NOT NULL,
  phone_number TEXT NOT NULL,
  name TEXT,
  last_interaction TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  is_locked BOOLEAN DEFAULT FALSE,
  PRIMARY KEY (session_name, phone_number)
);

-- 29. FB Comments (NEW)
CREATE TABLE IF NOT EXISTS fb_comments (
  comment_id TEXT PRIMARY KEY,
  page_id TEXT,
  sender_id TEXT,
  parent_id TEXT,
  post_id TEXT,
  message TEXT,
  reply_text TEXT,
  status TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 30. FB N8N Debounce (NEW)
CREATE TABLE IF NOT EXISTS fb_n8n_debounce (
  key TEXT PRIMARY KEY,
  incr INTEGER DEFAULT 1,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 31. Lite Engine Config (Optional)
CREATE TABLE IF NOT EXISTS lite_engine_config (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID REFERENCES users(id),
  enabled BOOLEAN DEFAULT FALSE,
  fallback_message TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 32. External API Keys (Optional)
CREATE TABLE IF NOT EXISTS external_api_keys (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID REFERENCES users(id),
  service_name TEXT,
  api_key TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 33. System Logs (Optional)
CREATE TABLE IF NOT EXISTS system_logs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  level TEXT DEFAULT 'info',
  message TEXT,
  metadata JSONB,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 34. WhatsApp Debounce (Added for dbService compatibility)
CREATE TABLE IF NOT EXISTS whatsapp_debounce (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  message_id TEXT NOT NULL UNIQUE,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 35. API Key List (For Key Rotation)
CREATE TABLE IF NOT EXISTS api_list (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  provider TEXT NOT NULL, -- 'google', 'openai', 'gemini'
  api TEXT NOT NULL, -- The API Key
  model TEXT DEFAULT 'gemini-2.5-flash',
  usage_count BIGINT DEFAULT 0,
  rpm_limit INTEGER DEFAULT 5,
  rpd_limit INTEGER DEFAULT 20,
  usage_today INTEGER DEFAULT 0,
  last_used_at TIMESTAMP WITH TIME ZONE,
  last_date_checked DATE DEFAULT CURRENT_DATE,
  status TEXT DEFAULT 'active',
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_api_list_provider ON api_list(provider);

-- 36. Lite Engine Keys
CREATE TABLE IF NOT EXISTS lite_engine_keys (
  id UUID DEFAULT uuid_generate_v4() PRIMARY KEY,
  api_key TEXT NOT NULL UNIQUE,
  provider TEXT DEFAULT 'groq',
  status TEXT DEFAULT 'active',
  total_tokens_used BIGINT DEFAULT 0,
  requests_today INTEGER DEFAULT 0,
  last_used_at TIMESTAMP WITH TIME ZONE,
  reset_at TIMESTAMP WITH TIME ZONE DEFAULT NOW() + INTERVAL '1 day',
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_lite_keys_status ON lite_engine_keys(status);
CREATE INDEX IF NOT EXISTS idx_lite_keys_last_used ON lite_engine_keys(last_used_at);

-- 37. User Integrations (WooCommerce)
CREATE TABLE IF NOT EXISTS user_integrations (
  user_id UUID PRIMARY KEY REFERENCES users(id),
  wc_url TEXT,
  wc_consumer_key TEXT,
  wc_consumer_secret TEXT,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 38. FB Contacts (For Locking)
CREATE TABLE IF NOT EXISTS fb_contacts (
  page_id TEXT NOT NULL,
  sender_id TEXT NOT NULL,
  name TEXT,
  is_locked BOOLEAN DEFAULT FALSE,
  last_interaction TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  PRIMARY KEY (page_id, sender_id)
);
