-- Enable pg_trgm extension for fuzzy search
CREATE EXTENSION IF NOT EXISTS pg_trgm;

-- Create Products Table
CREATE TABLE IF NOT EXISTS products (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID NOT NULL, -- Links to auth.users or your user_configs logic
    name TEXT NOT NULL,
    description TEXT,
    image_url TEXT,
    is_active BOOLEAN DEFAULT TRUE,
    price NUMERIC DEFAULT 0,
    stock INTEGER DEFAULT 0,
    currency TEXT DEFAULT 'BDT',
    variants JSONB DEFAULT '[]'::jsonb, -- Store [{name, price, stock}, ...]
    allowed_page_ids JSONB DEFAULT '[]'::jsonb, -- Store allowed page IDs
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Indexes for Search
CREATE INDEX IF NOT EXISTS idx_products_user_id ON products(user_id);
CREATE INDEX IF NOT EXISTS idx_products_name_trgm ON products USING gin (name gin_trgm_ops);
CREATE INDEX IF NOT EXISTS idx_products_description_trgm ON products USING gin (description gin_trgm_ops);

-- RLS Policies
ALTER TABLE products ENABLE ROW LEVEL SECURITY;

-- Policy: Users can only see/edit their own products
-- Note: These policies assume you are using Supabase Auth (auth.uid()).
-- If you are using custom auth, adjust accordingly.
CREATE POLICY "Users can view own products" ON products
    FOR SELECT USING (auth.uid() = user_id);

CREATE POLICY "Users can insert own products" ON products
    FOR INSERT WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users can update own products" ON products
    FOR UPDATE USING (auth.uid() = user_id);

CREATE POLICY "Users can delete own products" ON products
    FOR DELETE USING (auth.uid() = user_id);
