-- Fix WhatsApp Database Table and RLS
-- Run this in Supabase SQL Editor

-- 1. Ensure Table Exists
CREATE TABLE IF NOT EXISTS whatsapp_message_database (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    session_name TEXT NOT NULL UNIQUE,
    user_id UUID,
    email TEXT,
    active BOOLEAN DEFAULT TRUE,
    status TEXT DEFAULT 'created',
    reply_message BOOLEAN DEFAULT FALSE,
    swipe_reply BOOLEAN DEFAULT FALSE,
    order_tracking BOOLEAN DEFAULT FALSE,
    image_detection BOOLEAN DEFAULT FALSE,
    image_send BOOLEAN DEFAULT FALSE,
    audio_detection BOOLEAN DEFAULT FALSE,
    file_upload BOOLEAN DEFAULT FALSE,
    text_prompt TEXT,
    subscription_status TEXT DEFAULT 'active',
    expires_at TIMESTAMP WITH TIME ZONE,
    plan_days INTEGER DEFAULT 30,
    qr_code TEXT,
    api_key TEXT,
    cheap_engine BOOLEAN DEFAULT TRUE,
    block_emoji TEXT,
    unblock_emoji TEXT,
    group_reply BOOLEAN DEFAULT FALSE
);

-- 2. Enable RLS
ALTER TABLE whatsapp_message_database ENABLE ROW LEVEL SECURITY;

-- 3. Add Policies
-- Allow Users to View their own sessions
DROP POLICY IF EXISTS "Users can view their own sessions" ON whatsapp_message_database;
CREATE POLICY "Users can view their own sessions"
ON whatsapp_message_database
FOR SELECT
USING (auth.uid() = user_id);

-- Allow Users to Delete their own sessions
DROP POLICY IF EXISTS "Users can delete their own sessions" ON whatsapp_message_database;
CREATE POLICY "Users can delete their own sessions"
ON whatsapp_message_database
FOR DELETE
USING (auth.uid() = user_id);

-- Allow Users to Update their own sessions
DROP POLICY IF EXISTS "Users can update their own sessions" ON whatsapp_message_database;
CREATE POLICY "Users can update their own sessions"
ON whatsapp_message_database
FOR UPDATE
USING (auth.uid() = user_id);

-- 4. Fix Indexes
CREATE INDEX IF NOT EXISTS idx_whatsapp_msg_db_user ON whatsapp_message_database(user_id);
CREATE INDEX IF NOT EXISTS idx_whatsapp_msg_db_session ON whatsapp_message_database(session_name);

-- 5. Fix permissions (Grant access to authenticated users)
GRANT ALL ON whatsapp_message_database TO service_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON whatsapp_message_database TO authenticated;
