ALTER TABLE whatsapp_order_tracking
ADD COLUMN IF NOT EXISTS product_name TEXT,
ADD COLUMN IF NOT EXISTS number TEXT,
ADD COLUMN IF NOT EXISTS location TEXT,
ADD COLUMN IF NOT EXISTS product_quantity TEXT DEFAULT '1',
ADD COLUMN IF NOT EXISTS price NUMERIC;

ALTER TABLE whatsapp_chats
ADD COLUMN IF NOT EXISTS token_usage INTEGER DEFAULT 0,
ADD COLUMN IF NOT EXISTS model_used TEXT;
