import { useEffect, useState } from "react";
import { Loader2, ShoppingBag } from "lucide-react";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table";
import { BACKEND_URL } from "@/config";
import { toast } from "sonner";

type Order = { id: string; product_name?: string; product_quantity?: string | number; price?: string | number; customer_name?: string; number?: string; location?: string; status?: string; created_at?: string };
export default function InstagramOrderTrackingPage() { const accountId = localStorage.getItem("active_ig_account_id"); const [orders, setOrders] = useState<Order[]>([]); const [loading, setLoading] = useState(true); useEffect(() => { const load = async () => { if (!accountId) { setLoading(false); return; } try { const token = localStorage.getItem("auth_token"); const response = await fetch(`${BACKEND_URL}/api/instagram/orders?account_id=${encodeURIComponent(accountId)}`, { headers: token ? { Authorization: `Bearer ${token}` } : {} }); if (!response.ok) throw new Error("Instagram orders load করা যায়নি"); const data = await response.json(); setOrders(Array.isArray(data) ? data : []); } catch (error) { toast.error(error instanceof Error ? error.message : "Instagram orders load করা যায়নি"); } finally { setLoading(false); } }; void load(); }, [accountId]); if (loading) return <div className="flex min-h-[360px] items-center justify-center"><Loader2 className="animate-spin" /></div>; return <div className="space-y-6"><div><h1 className="text-3xl font-bold">Instagram Order Tracking</h1><p className="mt-1 text-muted-foreground">Instagram DM থেকে পাওয়া customer order দেখুন।</p></div><Card><CardHeader><CardTitle className="flex items-center gap-2"><ShoppingBag className="text-pink-500" />Order List</CardTitle><CardDescription>{accountId ? "Selected Instagram account-এর orders" : "প্রথমে একটি Instagram account select করুন"}</CardDescription></CardHeader><CardContent>{!accountId ? <p className="py-8 text-center text-muted-foreground">No Instagram account selected.</p> : orders.length === 0 ? <p className="py-8 text-center text-muted-foreground">কোনো Instagram order পাওয়া যায়নি।</p> : <Table><TableHeader><TableRow><TableHead>Date</TableHead><TableHead>Customer</TableHead><TableHead>Product</TableHead><TableHead>Qty</TableHead><TableHead>Price</TableHead><TableHead>Status</TableHead></TableRow></TableHeader><TableBody>{orders.map(order => <TableRow key={order.id}><TableCell>{order.created_at ? new Date(order.created_at).toLocaleString() : "-"}</TableCell><TableCell>{order.customer_name || order.number || "-"}</TableCell><TableCell>{order.product_name || "-"}</TableCell><TableCell>{order.product_quantity || "-"}</TableCell><TableCell>{order.price || "-"}</TableCell><TableCell>{order.status || "ongoing"}</TableCell></TableRow>)}</TableBody></Table>}</CardContent></Card></div>; }
