import { useEffect, useState } from "react";
import { Loader2, MessageSquare } from "lucide-react";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table";
import { BACKEND_URL } from "@/config";
import { toast } from "sonner";

type Message = { id: string; sender_id?: string; text?: string; reply_by?: string; status?: string; created_at?: string };
export default function InstagramConversionPage() { const accountId = localStorage.getItem("active_ig_account_id"); const [messages, setMessages] = useState<Message[]>([]); const [loading, setLoading] = useState(true); useEffect(() => { const load = async () => { if (!accountId) { setLoading(false); return; } try { const token = localStorage.getItem("auth_token"); const response = await fetch(`${BACKEND_URL}/api/instagram/chats?account_id=${encodeURIComponent(accountId)}`, { headers: token ? { Authorization: `Bearer ${token}` } : {} }); if (!response.ok) throw new Error("Instagram conversions load করা যায়নি"); const data = await response.json(); setMessages(Array.isArray(data?.data) ? data.data : Array.isArray(data) ? data : []); } catch (error) { toast.error(error instanceof Error ? error.message : "Instagram conversions load করা যায়নি"); } finally { setLoading(false); } }; void load(); }, [accountId]); if (loading) return <div className="flex min-h-[360px] items-center justify-center"><Loader2 className="animate-spin" /></div>; return <div className="space-y-6"><div><h1 className="text-3xl font-bold">Instagram Conversion</h1><p className="mt-1 text-muted-foreground">Instagram DM conversation ও bot reply history দেখুন।</p></div><Card><CardHeader><CardTitle className="flex items-center gap-2"><MessageSquare className="text-pink-500" />Message History</CardTitle><CardDescription>{accountId ? "Selected Instagram account-এর messages" : "প্রথমে একটি Instagram account select করুন"}</CardDescription></CardHeader><CardContent>{!accountId ? <p className="py-8 text-center text-muted-foreground">No Instagram account selected.</p> : messages.length === 0 ? <p className="py-8 text-center text-muted-foreground">কোনো message পাওয়া যায়নি।</p> : <Table><TableHeader><TableRow><TableHead>Time</TableHead><TableHead>Customer</TableHead><TableHead>Message</TableHead><TableHead>Reply By</TableHead><TableHead>Status</TableHead></TableRow></TableHeader><TableBody>{messages.map(message => <TableRow key={message.id}><TableCell>{message.created_at ? new Date(message.created_at).toLocaleString() : "-"}</TableCell><TableCell className="font-mono text-xs">{message.sender_id || "-"}</TableCell><TableCell>{message.text || "-"}</TableCell><TableCell>{message.reply_by || "customer"}</TableCell><TableCell>{message.status || "received"}</TableCell></TableRow>)}</TableBody></Table>}</CardContent></Card></div>; }
