const pgClient = require('./pgClient');

const BUSINESS_TYPES = new Set(['ecommerce', 'digital_service', 'appointment']);
const PLATFORMS = new Set(['messenger', 'whatsapp', 'instagram']);

function normalizeEmail(email) {
    return String(email || '').trim().toLowerCase();
}

function normalizeBusinessType(type) {
    const value = String(type || '').trim();
    return BUSINESS_TYPES.has(value) ? value : null;
}

function normalizeResources(resources = []) {
    if (!Array.isArray(resources)) return [];
    const seen = new Set();
    return resources
        .map((resource) => ({
            platform: String(resource?.platform || '').trim(),
            resource_id: String(resource?.resource_id || '').trim()
        }))
        .filter((resource) => resource.resource_id && PLATFORMS.has(resource.platform))
        .filter((resource) => {
            const key = `${resource.platform}:${resource.resource_id}`;
            if (seen.has(key)) return false;
            seen.add(key);
            return true;
        });
}

async function ensureSchema(client = pgClient) {
    await client.query(`
        CREATE TABLE IF NOT EXISTS business_profiles (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            user_id UUID,
            owner_email TEXT NOT NULL,
            name TEXT NOT NULL,
            business_type TEXT NOT NULL CHECK (business_type IN ('ecommerce', 'digital_service', 'appointment')),
            description TEXT,
            is_active BOOLEAN NOT NULL DEFAULT TRUE,
            created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
            updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
        );
        CREATE TABLE IF NOT EXISTS business_profile_resources (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            business_profile_id BIGINT NOT NULL REFERENCES business_profiles(id) ON DELETE CASCADE,
            platform TEXT NOT NULL CHECK (platform IN ('messenger', 'whatsapp', 'instagram')),
            resource_id TEXT NOT NULL,
            created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
            UNIQUE (business_profile_id, platform, resource_id)
        );
        CREATE INDEX IF NOT EXISTS idx_business_profiles_owner_email ON business_profiles(LOWER(owner_email));
        CREATE INDEX IF NOT EXISTS idx_business_profile_resources_lookup ON business_profile_resources(platform, resource_id);
        CREATE INDEX IF NOT EXISTS idx_business_profile_resources_profile ON business_profile_resources(business_profile_id);
    `);
}

function groupProfiles(rows) {
    const map = new Map();
    for (const row of rows) {
        if (!map.has(row.id)) {
            map.set(row.id, {
                id: row.id,
                user_id: row.user_id,
                owner_email: row.owner_email,
                name: row.name,
                business_type: row.business_type,
                description: row.description,
                is_active: row.is_active,
                created_at: row.created_at,
                updated_at: row.updated_at,
                resources: []
            });
        }
        if (row.resource_id) {
            map.get(row.id).resources.push({ platform: row.platform, resource_id: row.resource_id });
        }
    }
    return [...map.values()];
}

async function listProfiles({ userId, email, platform, resourceId }) {
    await ensureSchema();
    const ownerEmail = normalizeEmail(email);
    const params = [ownerEmail, String(userId || '')];
    const filters = [`(LOWER(bp.owner_email) = $1 OR bp.user_id::text = $2)`];

    if (platform && resourceId) {
        params.push(String(platform), String(resourceId));
        filters.push(`EXISTS (
            SELECT 1 FROM business_profile_resources bpr_filter
            WHERE bpr_filter.business_profile_id = bp.id
              AND bpr_filter.platform = $${params.length - 1}
              AND bpr_filter.resource_id = $${params.length}
        )`);
    }

    const { rows } = await pgClient.query(
        `SELECT bp.*, bpr.platform, bpr.resource_id
         FROM business_profiles bp
         LEFT JOIN business_profile_resources bpr ON bpr.business_profile_id = bp.id
         WHERE ${filters.join(' AND ')}
         ORDER BY bp.created_at DESC, bp.id DESC`,
        params
    );
    return groupProfiles(rows);
}

async function validateOwnedResources({ email, userId, resources }) {
    const ownerEmail = normalizeEmail(email);
    for (const resource of resources) {
        if (resource.platform === 'messenger') {
            const result = await pgClient.query(
                `SELECT page_id FROM page_access_token_message
                 WHERE page_id::text = $1 AND (LOWER(email) = $2 OR user_id::text = $3)
                 LIMIT 1`,
                [resource.resource_id, ownerEmail, String(userId || '')]
            );
            if (!result.rowCount) return { valid: false, error: `Unauthorized Messenger page: ${resource.resource_id}` };
        }
        if (resource.platform === 'whatsapp') {
            const result = await pgClient.query(
                `SELECT session_name FROM whatsapp_message_database
                 WHERE session_name = $1 AND (LOWER(email) = $2 OR user_id::text = $3)
                 LIMIT 1`,
                [resource.resource_id, ownerEmail, String(userId || '')]
            );
            if (!result.rowCount) return { valid: false, error: `Unauthorized WhatsApp session: ${resource.resource_id}` };
        }
        if (resource.platform === 'instagram') {
            const result = await pgClient.query(
                `SELECT instagram_account_id FROM instagram_accounts
                 WHERE instagram_account_id::text = $1 AND (LOWER(email) = $2 OR user_id::text = $3)
                 LIMIT 1`,
                [resource.resource_id, ownerEmail, String(userId || '')]
            );
            if (!result.rowCount) return { valid: false, error: `Unauthorized Instagram account: ${resource.resource_id}` };
        }
    }
    return { valid: true };
}

async function getProfileForResource({ platform, resourceId }) {
    if (!PLATFORMS.has(String(platform || '')) || !resourceId) return null;
    await ensureSchema();
    const { rows } = await pgClient.query(
        `SELECT bp.id, bp.name, bp.business_type, bp.description
         FROM business_profiles bp
         INNER JOIN business_profile_resources bpr ON bpr.business_profile_id = bp.id
         WHERE bp.is_active = TRUE
           AND bpr.platform = $1
           AND bpr.resource_id = $2
         ORDER BY bp.updated_at DESC, bp.id DESC
         LIMIT 1`,
        [String(platform), String(resourceId)]
    );
    return rows[0] || null;
}

async function saveProfile({ userId, email, payload, id = null }) {
    await ensureSchema();
    const ownerEmail = normalizeEmail(email);
    const name = String(payload?.name || '').trim();
    const businessType = normalizeBusinessType(payload?.business_type);
    const description = String(payload?.description || '').trim() || null;
    const isActive = payload?.is_active !== false;
    const resources = normalizeResources(payload?.resources);

    if (!ownerEmail) throw new Error('Authenticated user email is required');
    if (!name) throw new Error('Business name is required');
    if (!businessType) throw new Error('Invalid business type');

    const resourceValidation = await validateOwnedResources({ email: ownerEmail, userId, resources });
    if (!resourceValidation.valid) {
        const error = new Error(resourceValidation.error);
        error.statusCode = 403;
        throw error;
    }

    const client = await pgClient.getPool().connect();
    try {
        await client.query('BEGIN');
        let profile;
        if (id) {
            const result = await client.query(
                `UPDATE business_profiles
                 SET name = $1, business_type = $2, description = $3, is_active = $4, updated_at = NOW()
                 WHERE id = $5 AND (LOWER(owner_email) = $6 OR user_id::text = $7)
                 RETURNING *`,
                [name, businessType, description, isActive, id, ownerEmail, String(userId || '')]
            );
            if (!result.rowCount) {
                const error = new Error('Business profile not found');
                error.statusCode = 404;
                throw error;
            }
            profile = result.rows[0];
            await client.query('DELETE FROM business_profile_resources WHERE business_profile_id = $1', [id]);
        } else {
            const result = await client.query(
                `INSERT INTO business_profiles (user_id, owner_email, name, business_type, description, is_active)
                 VALUES ($1::uuid, $2, $3, $4, $5, $6)
                 RETURNING *`,
                [userId || null, ownerEmail, name, businessType, description, isActive]
            );
            profile = result.rows[0];
        }

        for (const resource of resources) {
            await client.query(
                `INSERT INTO business_profile_resources (business_profile_id, platform, resource_id)
                 VALUES ($1, $2, $3)
                 ON CONFLICT DO NOTHING`,
                [profile.id, resource.platform, resource.resource_id]
            );
        }
        await client.query('COMMIT');
        return (await listProfiles({ userId, email: ownerEmail })).find((item) => String(item.id) === String(profile.id));
    } catch (error) {
        await client.query('ROLLBACK');
        throw error;
    } finally {
        client.release();
    }
}

async function deleteProfile({ userId, email, id }) {
    await ensureSchema();
    const result = await pgClient.query(
        `DELETE FROM business_profiles
         WHERE id = $1 AND (LOWER(owner_email) = $2 OR user_id::text = $3)`,
        [id, normalizeEmail(email), String(userId || '')]
    );
    return result.rowCount > 0;
}

async function getResourceOptions({ userId, email }) {
    const ownerEmail = normalizeEmail(email);
    const [messenger, whatsapp, instagram] = await Promise.all([
        pgClient.query(
            `SELECT page_id::text AS resource_id, COALESCE(name, page_id::text) AS name, 'messenger' AS platform
             FROM page_access_token_message
             WHERE LOWER(email) = $1 OR user_id::text = $2
             ORDER BY name NULLS LAST`,
            [ownerEmail, String(userId || '')]
        ),
        pgClient.query(
            `SELECT session_name AS resource_id, session_name AS name, 'whatsapp' AS platform
             FROM whatsapp_message_database
             WHERE LOWER(email) = $1 OR user_id::text = $2
             ORDER BY session_name`,
            [ownerEmail, String(userId || '')]
        ),
        pgClient.query(
            `SELECT instagram_account_id::text AS resource_id, COALESCE(instagram_username, name, instagram_account_id::text) AS name, 'instagram' AS platform
             FROM instagram_accounts
             WHERE LOWER(email) = $1 OR user_id::text = $2
             ORDER BY name NULLS LAST`,
            [ownerEmail, String(userId || '')]
        ).catch(() => ({ rows: [] }))
    ]);
    return [...messenger.rows, ...whatsapp.rows, ...instagram.rows];
}

module.exports = {
    BUSINESS_TYPES,
    PLATFORMS,
    ensureSchema,
    listProfiles,
    saveProfile,
    deleteProfile,
    getResourceOptions,
    getProfileForResource
};
