const pgClient = require('./pgClient');
const dbService = require('./dbService');
const aiService = require('./aiService');
const facebookService = require('./facebookService');

const DEFAULT_PUBLIC_REPLY = 'বিস্তারিত জানতে আপনার inbox দেখুন।';
const DEFAULT_DM_PROMPT = `You are a sales assistant replying privately to a customer who commented on a social media post.
Use the mapped post/product context as the primary source of truth.
If product details are available, answer price/details/order questions clearly in Bangla.
If no product is mapped, ask which product they mean.
Never say the product is available unless the context confirms it.`;

async function ensureTables() {
  await pgClient.query(`
    CREATE TABLE IF NOT EXISTS comment_automation_configs (
      id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      platform TEXT NOT NULL,
      account_id TEXT NOT NULL,
      enabled BOOLEAN NOT NULL DEFAULT FALSE,
      public_reply_enabled BOOLEAN NOT NULL DEFAULT TRUE,
      dm_enabled BOOLEAN NOT NULL DEFAULT TRUE,
      ai_enabled BOOLEAN NOT NULL DEFAULT TRUE,
      public_reply_template TEXT NOT NULL DEFAULT '${DEFAULT_PUBLIC_REPLY.replace(/'/g, "''")}',
      dm_system_prompt TEXT NOT NULL DEFAULT '${DEFAULT_DM_PROMPT.replace(/'/g, "''")}',
      trigger_keywords TEXT[] NOT NULL DEFAULT ARRAY['price','dam','দাম','কত','details','বিস্তারিত','order','অর্ডার','inbox','ইনবক্স'],
      cooldown_hours INTEGER NOT NULL DEFAULT 24,
      created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
      updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
      UNIQUE(platform, account_id)
    );

    CREATE TABLE IF NOT EXISTS social_post_product_mappings (
      id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      platform TEXT NOT NULL,
      account_id TEXT NOT NULL,
      post_id TEXT NOT NULL,
      caption TEXT,
      media_url TEXT,
      product_ids TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[],
      is_active BOOLEAN NOT NULL DEFAULT TRUE,
      created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
      updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
      UNIQUE(platform, account_id, post_id)
    );

    CREATE TABLE IF NOT EXISTS comment_automation_events (
      id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      platform TEXT NOT NULL,
      account_id TEXT NOT NULL,
      post_id TEXT,
      comment_id TEXT NOT NULL,
      commenter_id TEXT,
      comment_text TEXT,
      product_ids TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[],
      public_reply_status TEXT DEFAULT 'pending',
      dm_status TEXT DEFAULT 'pending',
      public_reply_text TEXT,
      dm_text TEXT,
      error_message TEXT,
      created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
      updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
      UNIQUE(platform, comment_id)
    );
  `);
  await pgClient.query(`
    ALTER TABLE comment_automation_configs ADD COLUMN IF NOT EXISTS enabled BOOLEAN NOT NULL DEFAULT FALSE;
    ALTER TABLE comment_automation_configs ADD COLUMN IF NOT EXISTS public_reply_enabled BOOLEAN NOT NULL DEFAULT TRUE;
    ALTER TABLE comment_automation_configs ADD COLUMN IF NOT EXISTS dm_enabled BOOLEAN NOT NULL DEFAULT TRUE;
    ALTER TABLE comment_automation_configs ADD COLUMN IF NOT EXISTS ai_enabled BOOLEAN NOT NULL DEFAULT TRUE;
    ALTER TABLE comment_automation_configs ADD COLUMN IF NOT EXISTS public_reply_template TEXT NOT NULL DEFAULT '${DEFAULT_PUBLIC_REPLY.replace(/'/g, "''")}';
    ALTER TABLE comment_automation_configs ADD COLUMN IF NOT EXISTS dm_system_prompt TEXT NOT NULL DEFAULT '${DEFAULT_DM_PROMPT.replace(/'/g, "''")}';
    ALTER TABLE comment_automation_configs ADD COLUMN IF NOT EXISTS trigger_keywords TEXT[] NOT NULL DEFAULT ARRAY['price','dam','দাম','কত','details','বিস্তারিত','order','অর্ডার','inbox','ইনবক্স'];
    ALTER TABLE comment_automation_configs ADD COLUMN IF NOT EXISTS cooldown_hours INTEGER NOT NULL DEFAULT 24;
    ALTER TABLE social_post_product_mappings ADD COLUMN IF NOT EXISTS caption TEXT;
    ALTER TABLE social_post_product_mappings ADD COLUMN IF NOT EXISTS media_url TEXT;
    ALTER TABLE social_post_product_mappings ADD COLUMN IF NOT EXISTS product_ids TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[];
    ALTER TABLE social_post_product_mappings ADD COLUMN IF NOT EXISTS is_active BOOLEAN NOT NULL DEFAULT TRUE;
  `);
}

async function getConfig(platform, accountId) {
  await ensureTables();
  await pgClient.query(
    `INSERT INTO comment_automation_configs (platform, account_id)
     VALUES ($1, $2)
     ON CONFLICT (platform, account_id) DO NOTHING`,
    [platform, String(accountId)]
  );
  const { rows } = await pgClient.query(
    `SELECT * FROM comment_automation_configs WHERE platform = $1 AND account_id = $2 LIMIT 1`,
    [platform, String(accountId)]
  );
  return rows[0] || null;
}

async function updateConfig(platform, accountId, input) {
  await ensureTables();
  const current = await getConfig(platform, accountId);
  const next = { ...current, ...(input || {}) };
  const { rows } = await pgClient.query(
    `INSERT INTO comment_automation_configs
      (platform, account_id, enabled, public_reply_enabled, dm_enabled, ai_enabled, public_reply_template, dm_system_prompt, trigger_keywords, cooldown_hours)
     VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10)
     ON CONFLICT (platform, account_id) DO UPDATE SET
      enabled = EXCLUDED.enabled,
      public_reply_enabled = EXCLUDED.public_reply_enabled,
      dm_enabled = EXCLUDED.dm_enabled,
      ai_enabled = EXCLUDED.ai_enabled,
      public_reply_template = EXCLUDED.public_reply_template,
      dm_system_prompt = EXCLUDED.dm_system_prompt,
      trigger_keywords = EXCLUDED.trigger_keywords,
      cooldown_hours = EXCLUDED.cooldown_hours,
      updated_at = NOW()
     RETURNING *`,
    [
      platform,
      String(accountId),
      Boolean(next.enabled),
      next.public_reply_enabled !== false,
      next.dm_enabled !== false,
      next.ai_enabled !== false,
      next.public_reply_template || DEFAULT_PUBLIC_REPLY,
      next.dm_system_prompt || DEFAULT_DM_PROMPT,
      Array.isArray(next.trigger_keywords) ? next.trigger_keywords : String(next.trigger_keywords || '').split(',').map(s => s.trim()).filter(Boolean),
      Number(next.cooldown_hours || 24)
    ]
  );
  return rows[0];
}

async function listMappings(platform, accountId) {
  await ensureTables();
  const { rows } = await pgClient.query(
    `SELECT * FROM social_post_product_mappings WHERE platform = $1 AND account_id = $2 ORDER BY updated_at DESC`,
    [platform, String(accountId)]
  );
  return rows;
}

async function upsertMapping(platform, accountId, data) {
  await ensureTables();
  const productIds = Array.isArray(data.product_ids) ? data.product_ids.map(String) : [];
  const { rows } = await pgClient.query(
    `INSERT INTO social_post_product_mappings (platform, account_id, post_id, caption, media_url, product_ids, is_active)
     VALUES ($1,$2,$3,$4,$5,$6,$7)
     ON CONFLICT (platform, account_id, post_id) DO UPDATE SET
      caption = EXCLUDED.caption,
      media_url = EXCLUDED.media_url,
      product_ids = EXCLUDED.product_ids,
      is_active = EXCLUDED.is_active,
      updated_at = NOW()
     RETURNING *`,
    [platform, String(accountId), String(data.post_id), data.caption || null, data.media_url || null, productIds, data.is_active !== false]
  );
  return rows[0];
}

async function findPostContext(platform, accountId, postId) {
  await ensureTables();
  const { rows } = await pgClient.query(
    `SELECT * FROM social_post_product_mappings WHERE platform = $1 AND account_id = $2 AND post_id = $3 AND is_active = TRUE LIMIT 1`,
    [platform, String(accountId), String(postId)]
  );
  let mapping = rows[0] || null;

  if (!mapping && platform === 'messenger') {
    const ad = await dbService.getAdContext(postId, accountId).catch(() => null);
    if (ad) mapping = { post_id: postId, caption: ad.description, product_ids: Array.isArray(ad.linked_product_ids) ? ad.linked_product_ids : [] };
  }

  const products = [];
  for (const id of mapping?.product_ids || []) {
    const product = await dbService.getProductById(id).catch(() => null);
    if (product) products.push(product);
  }
  return { mapping, products };
}

function productSummary(products) {
  if (!products.length) return 'No mapped product found for this post.';
  return products.map((p) => {
    const variants = Array.isArray(p.variants) && p.variants.length
      ? `\nVariants: ${p.variants.map(v => `${v.name || 'Option'} ${v.price || ''} ${v.currency || p.currency || ''}`.trim()).join('; ')}`
      : '';
    return `Product ID: ${p.id}\nName: ${p.name}\nPrice: ${p.price || ''} ${p.currency || ''}\nDescription: ${p.description || ''}${variants}`;
  }).join('\n\n');
}

function shouldTrigger(config, text) {
  const raw = String(text || '').toLowerCase();
  const keywords = Array.isArray(config.trigger_keywords) ? config.trigger_keywords : [];
  if (!keywords.length) return true;
  return keywords.some((keyword) => raw.includes(String(keyword).toLowerCase()));
}

async function processCommentAutomationEvent(event) {
  const platform = event.platform;
  const accountId = String(event.accountId || '');
  const commentId = String(event.commentId || '');
  const commenterId = String(event.commenterId || '');
  const postId = String(event.postId || '');
  const commentText = String(event.commentText || '').trim();
  const accessToken = event.accessToken;

  if (!platform || !accountId || !commentId || !commenterId || !postId || !accessToken) return { skipped: true, reason: 'missing_required_fields' };

  const config = await getConfig(platform, accountId);
  if (!config?.enabled) return { skipped: true, reason: 'disabled' };
  if (!shouldTrigger(config, commentText)) return { skipped: true, reason: 'keyword_not_matched' };

  await ensureTables();
  const existing = await pgClient.query(`SELECT id FROM comment_automation_events WHERE platform = $1 AND comment_id = $2 LIMIT 1`, [platform, commentId]);
  if (existing.rows[0]) return { skipped: true, reason: 'duplicate_comment' };

  const context = await findPostContext(platform, accountId, postId);
  const productIds = context.products.map(p => String(p.id));
  const publicReply = config.public_reply_template || DEFAULT_PUBLIC_REPLY;
  let dmText = '';
  let publicStatus = 'skipped';
  let dmStatus = 'skipped';

  await pgClient.query(
    `INSERT INTO comment_automation_events (platform, account_id, post_id, comment_id, commenter_id, comment_text, product_ids)
     VALUES ($1,$2,$3,$4,$5,$6,$7)
     ON CONFLICT (platform, comment_id) DO NOTHING`,
    [platform, accountId, postId, commentId, commenterId, commentText, productIds]
  );

  try {
    if (config.public_reply_enabled) {
      await facebookService.replyToComment(commentId, publicReply, accessToken);
      publicStatus = 'sent';
    }

    if (config.dm_enabled) {
      if (config.ai_enabled) {
        const hiddenContext = `<comment_post_context>\nPost ID: ${postId}\nCaption: ${context.mapping?.caption || ''}\nComment: ${commentText}\nMapped Products:\n${productSummary(context.products)}\nInstruction: Reply privately with exact details from mapped products. If no mapped product exists, ask for clarification.\n</comment_post_context>`;
        const result = await aiService.generateResponse({
          pageId: accountId,
          userId: commenterId,
          userMessage: `${hiddenContext}\n\nCustomer comment: ${commentText}`,
          history: [],
          imageUrls: [],
          audioUrls: [],
          config: { ...event.accountConfig, text_prompt: config.dm_system_prompt || DEFAULT_DM_PROMPT },
          platform
        });
        dmText = typeof result === 'string' ? result : (result?.reply || result?.reply_text || '');
      }
      if (!dmText) dmText = `${productSummary(context.products)}\n\nঅর্ডার করতে চাইলে আপনার নাম, ফোন নম্বর ও ঠিকানা পাঠান।`;

      if (platform === 'instagram') {
        await facebookService.sendInstagramMessage(accountId, commenterId, dmText, accessToken);
      } else {
        await facebookService.sendMessage(accountId, commenterId, dmText, accessToken);
      }
      await dbService.saveFbChat({ page_id: accountId, sender_id: accountId, recipient_id: commenterId, message_id: `${platform}_comment_dm_${commentId}`, text: dmText, timestamp: Date.now(), status: 'sent', reply_by: 'bot', platform });
      dmStatus = 'sent';
    }

    await pgClient.query(
      `UPDATE comment_automation_events SET public_reply_status = $1, dm_status = $2, public_reply_text = $3, dm_text = $4, updated_at = NOW() WHERE platform = $5 AND comment_id = $6`,
      [publicStatus, dmStatus, publicReply, dmText, platform, commentId]
    );
    return { success: true, publicStatus, dmStatus };
  } catch (error) {
    await pgClient.query(
      `UPDATE comment_automation_events SET public_reply_status = $1, dm_status = $2, error_message = $3, updated_at = NOW() WHERE platform = $4 AND comment_id = $5`,
      [publicStatus, dmStatus, error.message, platform, commentId]
    );
    throw error;
  }
}

module.exports = {
  getConfig,
  updateConfig,
  listMappings,
  upsertMapping,
  processCommentAutomationEvent,
  ensureTables
};
