const pgClient = require('./pgClient');
const dbService = require('./dbService');
const aiService = require('./aiService');
const facebookService = require('./facebookService');

const DEFAULT_SYSTEM_PROMPT = `You are a social media comment automation assistant. Use Bangla for customer-facing text. Never invent product price, stock, or features.`;
const DEFAULT_PROMPT_COMMENT = `Customer comment er upor base kore short, helpful Bangla reply dao. Post context/product info thakle sudhu oi information use korbe. Unknown hole polite vabe inbox korte bolo.`;
const MAX_PUBLIC_REPLY_LENGTH = 1000;
const HIDE_MODES = new Set(['all', 'keyword_or_ai', 'keyword_only', 'ai_only']);

async function ensureTables() {
  await pgClient.query(`
    CREATE TABLE IF NOT EXISTS comment_automation_configs (
      id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      platform TEXT NOT NULL,
      account_id TEXT NOT NULL,
      enabled BOOLEAN NOT NULL DEFAULT FALSE,
      system_prompt TEXT NOT NULL DEFAULT '${DEFAULT_SYSTEM_PROMPT.replace(/'/g, "''")}',
      hide_keywords TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[],
      hide_ai_instruction TEXT NOT NULL DEFAULT '',
      hide_ai_enabled BOOLEAN NOT NULL DEFAULT FALSE,
      created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
      updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
      UNIQUE(platform, account_id)
    );
    CREATE TABLE IF NOT EXISTS social_post_product_mappings (
      id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      platform TEXT NOT NULL,
      account_id TEXT NOT NULL,
      post_id TEXT NOT NULL,
      caption TEXT,
      media_url TEXT,
      permalink_url TEXT,
      product_ids TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[],
      is_active BOOLEAN NOT NULL DEFAULT TRUE,
      auto_like BOOLEAN NOT NULL DEFAULT FALSE,
      auto_like_children_comment BOOLEAN NOT NULL DEFAULT FALSE,
      auto_reply BOOLEAN NOT NULL DEFAULT FALSE,
      auto_reply_children_comment BOOLEAN NOT NULL DEFAULT FALSE,
      auto_hidden BOOLEAN NOT NULL DEFAULT FALSE,
      auto_comment BOOLEAN NOT NULL DEFAULT FALSE,
      prompt_comment TEXT NOT NULL DEFAULT '${DEFAULT_PROMPT_COMMENT.replace(/'/g, "''")}',
      hide_keywords TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[],
      hide_ai_instruction TEXT NOT NULL DEFAULT '',
      hide_ai_enabled BOOLEAN NOT NULL DEFAULT FALSE,
      hide_match_mode TEXT NOT NULL DEFAULT 'keyword_or_ai',
      post_created_at TIMESTAMP WITH TIME ZONE,
      created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
      updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
      UNIQUE(platform, account_id, post_id)
    );
    CREATE TABLE IF NOT EXISTS comment_automation_events (
      id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      platform TEXT NOT NULL,
      account_id TEXT NOT NULL,
      post_id TEXT,
      comment_id TEXT NOT NULL,
      commenter_id TEXT,
      comment_text TEXT,
      product_ids TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[],
      public_reply_status TEXT DEFAULT 'pending',
      dm_status TEXT DEFAULT 'skipped',
      reaction_status TEXT DEFAULT 'pending',
      reaction_type TEXT,
      moderation_status TEXT DEFAULT 'pending',
      is_reply_comment BOOLEAN NOT NULL DEFAULT FALSE,
      decision JSONB,
      public_reply_text TEXT,
      dm_text TEXT,
      error_message TEXT,
      created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
      updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
      UNIQUE(platform, comment_id)
    );
  `);
  await pgClient.query(`
    ALTER TABLE comment_automation_configs ADD COLUMN IF NOT EXISTS enabled BOOLEAN NOT NULL DEFAULT FALSE;
    ALTER TABLE comment_automation_configs ADD COLUMN IF NOT EXISTS system_prompt TEXT NOT NULL DEFAULT '${DEFAULT_SYSTEM_PROMPT.replace(/'/g, "''")}';
    ALTER TABLE comment_automation_configs ADD COLUMN IF NOT EXISTS hide_keywords TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[];
    ALTER TABLE comment_automation_configs ADD COLUMN IF NOT EXISTS hide_ai_instruction TEXT NOT NULL DEFAULT '';
    ALTER TABLE comment_automation_configs ADD COLUMN IF NOT EXISTS hide_ai_enabled BOOLEAN NOT NULL DEFAULT FALSE;
    ALTER TABLE social_post_product_mappings ADD COLUMN IF NOT EXISTS caption TEXT;
    ALTER TABLE social_post_product_mappings ADD COLUMN IF NOT EXISTS media_url TEXT;
    ALTER TABLE social_post_product_mappings ADD COLUMN IF NOT EXISTS permalink_url TEXT;
    ALTER TABLE social_post_product_mappings ADD COLUMN IF NOT EXISTS product_ids TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[];
    ALTER TABLE social_post_product_mappings ADD COLUMN IF NOT EXISTS is_active BOOLEAN NOT NULL DEFAULT TRUE;
    ALTER TABLE social_post_product_mappings ADD COLUMN IF NOT EXISTS auto_like BOOLEAN NOT NULL DEFAULT FALSE;
    ALTER TABLE social_post_product_mappings ADD COLUMN IF NOT EXISTS auto_like_children_comment BOOLEAN NOT NULL DEFAULT FALSE;
    ALTER TABLE social_post_product_mappings ADD COLUMN IF NOT EXISTS auto_reply BOOLEAN NOT NULL DEFAULT FALSE;
    ALTER TABLE social_post_product_mappings ADD COLUMN IF NOT EXISTS auto_reply_children_comment BOOLEAN NOT NULL DEFAULT FALSE;
    ALTER TABLE social_post_product_mappings ADD COLUMN IF NOT EXISTS auto_hidden BOOLEAN NOT NULL DEFAULT FALSE;
    ALTER TABLE social_post_product_mappings ADD COLUMN IF NOT EXISTS auto_comment BOOLEAN NOT NULL DEFAULT FALSE;
    ALTER TABLE social_post_product_mappings ADD COLUMN IF NOT EXISTS prompt_comment TEXT NOT NULL DEFAULT '${DEFAULT_PROMPT_COMMENT.replace(/'/g, "''")}';
    ALTER TABLE social_post_product_mappings ADD COLUMN IF NOT EXISTS hide_keywords TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[];
    ALTER TABLE social_post_product_mappings ADD COLUMN IF NOT EXISTS hide_ai_instruction TEXT NOT NULL DEFAULT '';
    ALTER TABLE social_post_product_mappings ADD COLUMN IF NOT EXISTS hide_ai_enabled BOOLEAN NOT NULL DEFAULT FALSE;
    ALTER TABLE social_post_product_mappings ADD COLUMN IF NOT EXISTS hide_match_mode TEXT NOT NULL DEFAULT 'keyword_or_ai';
    ALTER TABLE social_post_product_mappings ADD COLUMN IF NOT EXISTS post_created_at TIMESTAMP WITH TIME ZONE;
    ALTER TABLE comment_automation_events ADD COLUMN IF NOT EXISTS reaction_status TEXT DEFAULT 'pending';
    ALTER TABLE comment_automation_events ADD COLUMN IF NOT EXISTS reaction_type TEXT;
    ALTER TABLE comment_automation_events ADD COLUMN IF NOT EXISTS moderation_status TEXT DEFAULT 'pending';
    ALTER TABLE comment_automation_events ADD COLUMN IF NOT EXISTS is_reply_comment BOOLEAN NOT NULL DEFAULT FALSE;
    ALTER TABLE comment_automation_events ADD COLUMN IF NOT EXISTS decision JSONB;
  `);
}

function bool(value) {
  return value === true || value === 'true' || value === 1 || value === '1';
}

function normalizeKeywords(value) {
  const list = Array.isArray(value) ? value : String(value || '').split(/[\n,]/);
  return [...new Set(list.map((item) => String(item || '').trim().toLowerCase()).filter(Boolean))];
}

function normalizeHideMode(value) {
  const mode = String(value || 'keyword_or_ai').trim();
  return HIDE_MODES.has(mode) ? mode : 'keyword_or_ai';
}

function keywordMatches(commentText, keywords) {
  const normalizedText = String(commentText || '').toLowerCase();
  return normalizeKeywords(keywords).filter((keyword) => normalizedText.includes(keyword));
}

function parseHideDecision(value) {
  const rawValue = typeof value === 'string' ? value : (value?.output ?? value?.hide ?? value?.reply ?? value?.text ?? value?.response ?? value?.message ?? '');
  if (typeof rawValue === 'boolean') return { hide: rawValue, reason: rawValue ? 'ai_true' : 'ai_false' };

  const cleaned = String(rawValue || '').replace(/```json|```/gi, '').trim();
  const lowered = cleaned.toLowerCase();
  if (['true', 'yes', 'hide'].includes(lowered)) return { hide: true, reason: 'ai_true' };
  if (['false', 'no', 'skip', 'do not hide'].includes(lowered)) return { hide: false, reason: 'ai_false' };

  try {
    const parsed = JSON.parse(cleaned.match(/\{[\s\S]*\}/)?.[0] || cleaned);
    const decision = parsed.hide ?? parsed.hidden ?? parsed.output ?? parsed.shouldHide ?? parsed.should_hide;
    if (typeof decision === 'boolean') return { hide: decision, reason: String(parsed.reason || (decision ? 'ai_true' : 'ai_false')).slice(0, 250) };
    if (typeof decision === 'string') {
      const normalized = decision.trim().toLowerCase();
      if (['true', 'yes', 'hide'].includes(normalized)) return { hide: true, reason: String(parsed.reason || 'ai_true').slice(0, 250) };
      if (['false', 'no', 'skip', 'do not hide'].includes(normalized)) return { hide: false, reason: String(parsed.reason || 'ai_false').slice(0, 250) };
    }
  } catch (_) {
    if (/\bhide\b/.test(lowered) && !/\b(no|not|false|skip)\b/.test(lowered)) {
      return { hide: true, reason: 'ai_text_hide' };
    }
  }
  return { hide: false, reason: 'ai_parse_failed' };
}

function normalizeObfuscatedText(value) {
  return String(value || '')
    .toLowerCase()
    .replace(/[._\-\s]+/g, '')
    .replace(/[@]/g, 'a')
    .replace(/[0]/g, 'o')
    .replace(/[1!|]/g, 'i')
    .replace(/[3]/g, 'e')
    .replace(/[4]/g, 'a')
    .replace(/[5$]/g, 's')
    .replace(/[7]/g, 't');
}

function normalizeRepeatSignature(value) {
  return normalizeObfuscatedText(value)
    .replace(/[^a-z0-9\u0980-\u09ff]+/g, '')
    .slice(0, 500);
}

function isSameRepeatComment(a, b) {
  const left = normalizeRepeatSignature(a);
  const right = normalizeRepeatSignature(b);
  if (!left || !right) return false;
  if (left === right) return true;
  const longer = left.length >= right.length ? left : right;
  const shorter = left.length >= right.length ? right : left;
  return shorter.length >= 12 && longer.includes(shorter);
}

async function findRepeatedComment({ platform, accountId, postId, commenterId, commentId, commentText }) {
  const { rows } = await pgClient.query(
    `SELECT comment_id, comment_text, created_at
     FROM comment_automation_events
     WHERE platform = $1
       AND account_id = $2
       AND post_id = $3
       AND commenter_id = $4
       AND comment_id <> $5
       AND created_at >= NOW() - INTERVAL '30 days'
     ORDER BY created_at ASC
     LIMIT 100`,
    [platform, String(accountId), String(postId), String(commenterId), String(commentId)]
  );
  const repeats = rows.filter((row) => isSameRepeatComment(row.comment_text, commentText));
  return { isRepeat: repeats.length > 0, repeatCount: repeats.length + 1, firstCommentId: repeats[0]?.comment_id || null };
}

function buildHidePrompt({ commentText, postId, isReplyComment, caption, globalInstruction, postInstruction, keywords, mode }) {
  const normalizedComment = normalizeObfuscatedText(commentText);
  return `You are a Facebook comment moderation judge for a business page.

Task:
Read the business owner's hide policy and the full user comment in context.
Decide if this exact comment should be hidden from the public page.
Output true only when the full meaning, intent, and business policy say it should be hidden.
Output false when the comment is positive, neutral, a genuine question, or criticism that the business policy does not ask to hide.

Output rule:
Return ONLY one word: true or false.
No markdown. No explanation.

Business owner's hide policy:
Global policy: ${globalInstruction || 'Hide abusive, vulgar, fake bad review, false product-not-working claim, spam, scam, competitor promotion, or harmful comments.'}
Post policy: ${postInstruction || 'No extra post-specific policy.'}
Configured signals/keywords to consider contextually, not blindly: ${keywords.length ? keywords.join(', ') : 'none'}
Hide mode: ${mode}

Important intelligence rules:
- Understand Bangla, Banglish, English, slang, misspellings, sarcasm, and obfuscated words.
- Do not hide only because one bad word appears; judge the full sentence sentiment and intent.
- Example: "what the fuck this is amazing" is positive praise, so output false unless the business policy says to hide all vulgar words regardless of sentiment.
- Example: "product ta kaj kortese na" may be a product-not-working claim; hide only if the business policy says to hide such claims.
- Detect same meaning even if exact keyword is not present.
- Do not hide genuine customer questions, order questions, price questions, or real support requests unless the policy says to hide them.

Context:
Post ID: ${postId}
Is child/reply comment: ${isReplyComment ? 'yes' : 'no'}
Post caption: ${caption || ''}
Original customer comment: ${commentText}
Normalized comment for bypass detection: ${normalizedComment}`;
}

async function getConfig(platform, accountId) {
  await ensureTables();
  await pgClient.query(`INSERT INTO comment_automation_configs (platform, account_id) VALUES ($1, $2) ON CONFLICT (platform, account_id) DO NOTHING`, [platform, String(accountId)]);
  const { rows } = await pgClient.query(`SELECT platform, account_id, enabled, system_prompt, hide_keywords, hide_ai_instruction, hide_ai_enabled, created_at, updated_at FROM comment_automation_configs WHERE platform = $1 AND account_id = $2 LIMIT 1`, [platform, String(accountId)]);
  return rows[0] || null;
}

async function updateConfig(platform, accountId, input) {
  await ensureTables();
  const current = await getConfig(platform, accountId);
  const enabled = input?.enabled === undefined ? Boolean(current?.enabled) : Boolean(input.enabled);
  const systemPrompt = String(input?.system_prompt || current?.system_prompt || DEFAULT_SYSTEM_PROMPT).trim() || DEFAULT_SYSTEM_PROMPT;
  const hideKeywords = input?.hide_keywords === undefined ? normalizeKeywords(current?.hide_keywords || []) : normalizeKeywords(input.hide_keywords);
  const hideAiInstruction = input?.hide_ai_instruction === undefined ? String(current?.hide_ai_instruction || '') : String(input.hide_ai_instruction || '').trim();
  const hideAiEnabled = input?.hide_ai_enabled === undefined ? Boolean(current?.hide_ai_enabled) : bool(input.hide_ai_enabled);
  const { rows } = await pgClient.query(
    `INSERT INTO comment_automation_configs (platform, account_id, enabled, system_prompt, hide_keywords, hide_ai_instruction, hide_ai_enabled)
     VALUES ($1, $2, $3, $4, $5, $6, $7)
     ON CONFLICT (platform, account_id) DO UPDATE SET enabled = EXCLUDED.enabled, system_prompt = EXCLUDED.system_prompt, hide_keywords = EXCLUDED.hide_keywords, hide_ai_instruction = EXCLUDED.hide_ai_instruction, hide_ai_enabled = EXCLUDED.hide_ai_enabled, updated_at = NOW()
     RETURNING platform, account_id, enabled, system_prompt, hide_keywords, hide_ai_instruction, hide_ai_enabled, created_at, updated_at`,
    [platform, String(accountId), enabled, systemPrompt, hideKeywords, hideAiInstruction, hideAiEnabled]
  );
  return rows[0];
}

async function listMappings(platform, accountId) {
  await ensureTables();
  const { rows } = await pgClient.query(`SELECT * FROM social_post_product_mappings WHERE platform = $1 AND account_id = $2 ORDER BY COALESCE(post_created_at, updated_at) DESC`, [platform, String(accountId)]);
  return rows;
}

async function hydrateMappingPostDetails(platform, data, accessToken) {
  if (platform !== 'messenger' || !accessToken || !data?.post_id) return data;
  if (data.caption && data.media_url && data.permalink_url && data.post_created_at) return data;

  const post = await facebookService.getPostDetails(String(data.post_id), accessToken);
  if (!post) return data;

  return {
    ...data,
    caption: data.caption || post.message || post.story || '',
    media_url: data.media_url || post.full_picture || post.picture || '',
    permalink_url: data.permalink_url || post.permalink_url || '',
    post_created_at: data.post_created_at || post.created_time || null
  };
}

async function upsertMapping(platform, accountId, data, options = {}) {
  await ensureTables();
  data = await hydrateMappingPostDetails(platform, data, options.accessToken);
  const productIds = Array.isArray(data.product_ids) ? data.product_ids.map(String) : [];
  const promptComment = String(data.prompt_comment || DEFAULT_PROMPT_COMMENT).trim() || DEFAULT_PROMPT_COMMENT;
  const hideKeywords = normalizeKeywords(data.hide_keywords || []);
  const hideAiInstruction = String(data.hide_ai_instruction || '').trim();
  const hideMatchMode = normalizeHideMode(data.hide_match_mode);
  const { rows } = await pgClient.query(
    `INSERT INTO social_post_product_mappings (
       platform, account_id, post_id, caption, media_url, permalink_url, product_ids, is_active,
       auto_like, auto_like_children_comment, auto_reply, auto_reply_children_comment, auto_hidden, auto_comment, prompt_comment,
       hide_keywords, hide_ai_instruction, hide_ai_enabled, hide_match_mode, post_created_at
     ) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15,$16,$17,$18,$19,$20)
     ON CONFLICT (platform, account_id, post_id) DO UPDATE SET
       caption = COALESCE(EXCLUDED.caption, social_post_product_mappings.caption),
       media_url = COALESCE(EXCLUDED.media_url, social_post_product_mappings.media_url),
       permalink_url = COALESCE(EXCLUDED.permalink_url, social_post_product_mappings.permalink_url),
       product_ids = EXCLUDED.product_ids,
       is_active = EXCLUDED.is_active,
       auto_like = EXCLUDED.auto_like,
       auto_like_children_comment = EXCLUDED.auto_like_children_comment,
       auto_reply = EXCLUDED.auto_reply,
       auto_reply_children_comment = EXCLUDED.auto_reply_children_comment,
       auto_hidden = EXCLUDED.auto_hidden,
       auto_comment = EXCLUDED.auto_comment,
       prompt_comment = EXCLUDED.prompt_comment,
       hide_keywords = EXCLUDED.hide_keywords,
       hide_ai_instruction = EXCLUDED.hide_ai_instruction,
       hide_ai_enabled = EXCLUDED.hide_ai_enabled,
       hide_match_mode = EXCLUDED.hide_match_mode,
       post_created_at = COALESCE(EXCLUDED.post_created_at, social_post_product_mappings.post_created_at),
       updated_at = NOW()
     RETURNING *`,
    [
      platform,
      String(accountId),
      String(data.post_id),
      data.caption || null,
      data.media_url || null,
      data.permalink_url || null,
      productIds,
      data.is_active !== false,
      bool(data.auto_like),
      bool(data.auto_like_children_comment),
      bool(data.auto_reply),
      bool(data.auto_reply_children_comment),
      bool(data.auto_hidden),
      bool(data.auto_comment),
      promptComment,
      hideKeywords,
      hideAiInstruction,
      bool(data.hide_ai_enabled),
      hideMatchMode,
      data.post_created_at || null
    ]
  );
  return rows[0];
}

async function deleteMapping(platform, accountId, mappingId) {
  await ensureTables();
  const { rows } = await pgClient.query(`DELETE FROM social_post_product_mappings WHERE platform = $1 AND account_id = $2 AND (id::text = $3 OR post_id = $3) RETURNING *`, [platform, String(accountId), String(mappingId)]);
  return rows[0] || null;
}

async function listEvents(platform, accountId) {
  await ensureTables();
  const { rows } = await pgClient.query(`SELECT * FROM comment_automation_events WHERE platform = $1 AND account_id = $2 ORDER BY created_at DESC LIMIT 50`, [platform, String(accountId)]);
  return rows;
}

async function syncFacebookPosts(platform, accountId, accessToken) {
  await ensureTables();
  if (platform !== 'messenger') return { synced: 0, posts: [] };
  const posts = await facebookService.listPagePosts(accountId, accessToken, { limit: 10, maxPages: 5 });
  const saved = [];
  for (const post of posts) {
    const existing = await pgClient.query(
      `SELECT * FROM social_post_product_mappings WHERE platform = $1 AND account_id = $2 AND post_id = $3 LIMIT 1`,
      [platform, String(accountId), String(post.id)]
    );
    const current = existing.rows[0] || {};
    saved.push(await upsertMapping(platform, accountId, {
      post_id: post.id,
      caption: post.message || post.story || current.caption || '',
      media_url: post.full_picture || post.picture || current.media_url || '',
      permalink_url: post.permalink_url || current.permalink_url || '',
      product_ids: current.product_ids || [],
      is_active: current.is_active !== undefined ? current.is_active : true,
      auto_like: Boolean(current.auto_like),
      auto_like_children_comment: Boolean(current.auto_like_children_comment),
      auto_reply: Boolean(current.auto_reply),
      auto_reply_children_comment: Boolean(current.auto_reply_children_comment),
      auto_hidden: Boolean(current.auto_hidden),
      auto_comment: Boolean(current.auto_comment),
      prompt_comment: current.prompt_comment || DEFAULT_PROMPT_COMMENT,
      hide_keywords: current.hide_keywords || [],
      hide_ai_instruction: current.hide_ai_instruction || '',
      hide_ai_enabled: Boolean(current.hide_ai_enabled),
      hide_match_mode: current.hide_match_mode || 'keyword_or_ai',
      post_created_at: post.created_time || current.post_created_at || null
    }));
  }
  return { synced: saved.length, posts: saved };
}

async function findPostContext(platform, accountId, postId) {
  await ensureTables();
  const { rows } = await pgClient.query(`SELECT * FROM social_post_product_mappings WHERE platform = $1 AND account_id = $2 AND post_id = $3 AND is_active = TRUE LIMIT 1`, [platform, String(accountId), String(postId)]);
  let mapping = rows[0] || null;
  if (!mapping && platform === 'messenger') {
    const ad = await dbService.getAdContext(postId, accountId).catch(() => null);
    if (ad) mapping = { post_id: postId, caption: ad.description, product_ids: Array.isArray(ad.linked_product_ids) ? ad.linked_product_ids : [] };
  }
  const products = [];
  for (const id of mapping?.product_ids || []) {
    const product = await dbService.getProductById(id).catch(() => null);
    if (product) products.push(product);
  }
  return { mapping, products };
}

function productSummary(products) {
  if (!products.length) return 'No mapped product found for this post.';
  return products.map((product) => `Product ID: ${product.id}\nName: ${product.name}\nPrice: ${product.price || ''} ${product.currency || ''}\nDescription: ${product.description || ''}`).join('\n\n');
}

function buildReplyPrompt({ platform, postId, commentText, context, products, systemPrompt, isReplyComment }) {
  return `${systemPrompt}\n\n${context.mapping?.prompt_comment || DEFAULT_PROMPT_COMMENT}\n\nReturn only the reply text.\n\n<context>\nPlatform: ${platform}\nPost ID: ${postId}\nIs reply/child comment: ${isReplyComment ? 'yes' : 'no'}\nPost caption: ${context.mapping?.caption || ''}\nCustomer comment: ${commentText}\nMapped products:\n${productSummary(products)}\n</context>`;
}

function cleanReply(value) {
  const text = typeof value === 'string' ? value : (value?.reply_text || value?.reply || value?.message || value?.response || '');
  return String(text || '').replace(/```[\s\S]*?```/g, '').trim().slice(0, MAX_PUBLIC_REPLY_LENGTH);
}

async function evaluateHideRules({ config, mapping, commentText, postId, isReplyComment, accountConfig, platform, accountId, commenterId }) {
  if (!mapping?.auto_hidden) return { shouldHide: false, reason: 'hide_disabled', matchedKeywords: [], mode: 'keyword_or_ai', aiHide: false, aiReason: '' };

  const mode = normalizeHideMode(mapping?.hide_match_mode);
  const keywords = normalizeKeywords([...(config?.hide_keywords || []), ...(mapping?.hide_keywords || [])]);
  const matchedKeywords = keywordMatches(commentText, keywords);
  if (mode === 'all') return { shouldHide: true, reason: 'hide_all_enabled', matchedKeywords, mode, aiHide: false, aiReason: '' };

  let aiHide = false;
  let aiReason = '';
  try {
    const result = await aiService.generateResponse({
      pageId: accountId,
      userId: commenterId || 'comment_moderation',
      userMessage: buildHidePrompt({
        commentText,
        postId,
        isReplyComment,
        caption: mapping?.caption || '',
        globalInstruction: config?.hide_ai_instruction || '',
        postInstruction: mapping?.hide_ai_instruction || '',
        keywords,
        mode
      }),
      history: [],
      imageUrls: [],
      audioUrls: [],
      config: { ...accountConfig, text_prompt: 'You are a strict comment moderation judge. Return only one word: true or false.' },
      platform
    });
    const parsed = parseHideDecision(result);
    aiHide = parsed.hide;
    aiReason = parsed.reason;
  } catch (error) {
    aiReason = `ai_error: ${error.message}`;
  }

  return {
    shouldHide: aiHide,
    reason: aiHide ? 'llm_policy_match' : 'llm_policy_no_match',
    matchedKeywords,
    mode,
    aiHide,
    aiReason
  };
}

async function updateEvent(platform, commentId, values) {
  await pgClient.query(
    `UPDATE comment_automation_events SET public_reply_status = $1, dm_status = $2, reaction_status = $3, reaction_type = $4, moderation_status = $5, public_reply_text = $6, dm_text = $7, decision = $8, error_message = $9, updated_at = NOW() WHERE platform = $10 AND comment_id = $11`,
    [values.publicStatus, values.dmStatus || 'skipped', values.reactionStatus, values.reactionType || null, values.moderationStatus || 'skipped', values.publicReplyText || null, null, JSON.stringify(values.decision || {}), values.errors?.join(' | ') || null, platform, commentId]
  );
}

async function insertSkippedEvent({ platform, accountId, postId, commentId, commenterId, commentText, isReplyComment, reason, errorMessage }) {
  if (!platform || !accountId || !commentId) return;
  await ensureTables();
  const decision = { action: 'SKIP', reason, received_post_id: postId || null };
  await pgClient.query(
    `INSERT INTO comment_automation_events
      (platform, account_id, post_id, comment_id, commenter_id, comment_text, product_ids, public_reply_status, dm_status, reaction_status, moderation_status, is_reply_comment, decision, error_message)
     VALUES ($1,$2,$3,$4,$5,$6,$7,'skipped','skipped','skipped','skipped',$8,$9,$10)
     ON CONFLICT (platform, comment_id) DO NOTHING`,
    [platform, accountId, postId || null, commentId, commenterId || null, commentText || null, [], Boolean(isReplyComment), JSON.stringify(decision), errorMessage || reason]
  );
}

async function processCommentAutomationEvent(event) {
  const platform = String(event.platform || '');
  const accountId = String(event.accountId || '');
  const commentId = String(event.commentId || '');
  const commenterId = String(event.commenterId || '');
  const postId = String(event.postId || '');
  const parentId = String(event.parentId || postId);
  const commentText = String(event.commentText || '').trim();
  const accessToken = event.accessToken;
  const isReplyComment = Boolean(event.isReplyComment ?? (parentId && postId && parentId !== postId));
  if (!platform || !accountId || !commentId || !commenterId || !postId || !accessToken) {
    await insertSkippedEvent({ platform, accountId, postId, commentId, commenterId, commentText, isReplyComment, reason: 'missing_required_fields' });
    return { skipped: true, reason: 'missing_required_fields' };
  }

  const config = await getConfig(platform, accountId);
  if (!config?.enabled) {
    await insertSkippedEvent({ platform, accountId, postId, commentId, commenterId, commentText, isReplyComment, reason: 'automation_disabled' });
    return { skipped: true, reason: 'disabled' };
  }
  const existing = await pgClient.query(`SELECT id FROM comment_automation_events WHERE platform = $1 AND comment_id = $2 LIMIT 1`, [platform, commentId]);
  if (existing.rows[0]) return { skipped: true, reason: 'duplicate_comment' };

  const context = await findPostContext(platform, accountId, postId);
  const mapping = context.mapping;
  if (!mapping?.is_active) {
    await insertSkippedEvent({ platform, accountId, postId, commentId, commenterId, commentText, isReplyComment, reason: 'post_not_configured', errorMessage: `No active post mapping found for ${postId}` });
    return { skipped: true, reason: 'post_not_configured' };
  }

  const productIds = context.products.map((product) => String(product.id));
  await pgClient.query(`INSERT INTO comment_automation_events (platform, account_id, post_id, comment_id, commenter_id, comment_text, product_ids, is_reply_comment) VALUES ($1,$2,$3,$4,$5,$6,$7,$8) ON CONFLICT (platform, comment_id) DO NOTHING`, [platform, accountId, postId, commentId, commenterId, commentText, productIds, isReplyComment]);

  const repeatDecision = Boolean(mapping.auto_hidden)
    ? await findRepeatedComment({ platform, accountId, postId, commenterId, commentId, commentText })
    : { isRepeat: false, repeatCount: 1, firstCommentId: null };
  const hideDecision = repeatDecision.isRepeat
    ? { shouldHide: true, reason: 'repeat_comment_memory', matchedKeywords: [], mode: 'comment_memory', aiHide: false, aiReason: `repeat_count:${repeatDecision.repeatCount}` }
    : await evaluateHideRules({ config, mapping, commentText, postId, isReplyComment, accountConfig: event.accountConfig, platform, accountId, commenterId });
  const shouldHide = hideDecision.shouldHide;
  const shouldLike = !shouldHide && Boolean(mapping.auto_like) && (!isReplyComment || Boolean(mapping.auto_like_children_comment));
  const shouldReply = !shouldHide && Boolean(mapping.auto_reply) && (!isReplyComment || Boolean(mapping.auto_reply_children_comment));
  const errors = [];
  let publicStatus = 'skipped';
  let reactionStatus = 'skipped';
  let moderationStatus = 'skipped';
  let publicReplyText = '';

  const decision = {
    action: shouldHide ? 'MODERATE' : shouldReply || shouldLike ? 'ENGAGE' : 'SKIP',
    auto_like: shouldLike,
    auto_reply: shouldReply,
    auto_hidden: shouldHide,
    auto_comment: Boolean(mapping.auto_comment),
    hide_mode: hideDecision.mode,
    hide_reason: hideDecision.reason,
    hide_matched_keywords: hideDecision.matchedKeywords,
    hide_ai_enabled: Boolean(config.hide_ai_enabled) || Boolean(mapping.hide_ai_enabled),
    hide_ai_reason: hideDecision.aiReason,
    repeat_comment: repeatDecision.isRepeat,
    repeat_count: repeatDecision.repeatCount,
    first_repeat_comment_id: repeatDecision.firstCommentId,
    reason: shouldHide ? 'hide_first_stop_engagement' : 'n8n_style_post_toggle_flow'
  };

  if (shouldHide) {
    try {
      await facebookService.hideComment(commentId, accessToken, true);
      moderationStatus = 'hidden';
    } catch (error) {
      moderationStatus = 'failed';
      errors.push(`hide: ${error.message}`);
    }
    await updateEvent(platform, commentId, { publicStatus, reactionStatus, reactionType: null, moderationStatus, publicReplyText, decision, errors });
    return { success: errors.length === 0, publicStatus, reactionStatus, moderationStatus, decision, errors };
  }

  if (shouldLike) {
    try {
      await facebookService.likeComment(commentId, accessToken);
      reactionStatus = 'sent';
    } catch (error) {
      reactionStatus = 'failed';
      errors.push(`like: ${error.message}`);
    }
  }

  if (shouldReply) {
    try {
      const result = await aiService.generateResponse({
        pageId: accountId,
        userId: commenterId,
        userMessage: buildReplyPrompt({ platform, postId, commentText, context, products: context.products, systemPrompt: config.system_prompt || DEFAULT_SYSTEM_PROMPT, isReplyComment }),
        history: [],
        imageUrls: [],
        audioUrls: [],
        config: { ...event.accountConfig, text_prompt: config.system_prompt || DEFAULT_SYSTEM_PROMPT },
        platform
      });
      publicReplyText = cleanReply(result);
      if (publicReplyText) {
        const replyResult = await facebookService.replyToComment(commentId, publicReplyText, accessToken);
        publicStatus = 'sent';
        if (platform === 'messenger' && replyResult?.id) {
          await facebookService.likeComment(replyResult.id, accessToken).catch((error) => errors.push(`reply_like: ${error.message}`));
        }
      }
    } catch (error) {
      publicStatus = 'failed';
      errors.push(`reply: ${error.message}`);
    }
  }

  await updateEvent(platform, commentId, { publicStatus, reactionStatus, reactionType: shouldLike ? 'LIKE' : null, moderationStatus, publicReplyText, decision, errors });
  return { success: errors.length === 0, publicStatus, reactionStatus, moderationStatus, decision, errors };
}

module.exports = { getConfig, updateConfig, listMappings, upsertMapping, deleteMapping, listEvents, syncFacebookPosts, processCommentAutomationEvent, ensureTables };
