const { query } = require('./pgClient');

let ensured = false;

async function ensureTrainingDatasetTable() {
    if (ensured) return;

    await query(`
        CREATE TABLE IF NOT EXISTS training_dataset_events (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
            platform TEXT NOT NULL,
            business_id TEXT,
            user_id TEXT,
            system_prompt TEXT,
            conversation_history JSONB DEFAULT '[]'::jsonb,
            user_message TEXT NOT NULL,
            assistant_reply TEXT NOT NULL,
            reasoning JSONB DEFAULT '{}'::jsonb,
            agentic_output JSONB DEFAULT '{}'::jsonb,
            available_tools JSONB DEFAULT '[]'::jsonb,
            tool_calls JSONB DEFAULT '[]'::jsonb,
            tool_results JSONB DEFAULT '[]'::jsonb,
            backend_actions JSONB DEFAULT '{}'::jsonb,
            model_used TEXT,
            source_message_id TEXT,
            quality_status TEXT NOT NULL DEFAULT 'pending',
            review_notes TEXT,
            reviewed_by TEXT,
            reviewed_at TIMESTAMP WITH TIME ZONE,
            metadata JSONB DEFAULT '{}'::jsonb
        );
        ALTER TABLE training_dataset_events ADD COLUMN IF NOT EXISTS agentic_output JSONB DEFAULT '{}'::jsonb;
        ALTER TABLE training_dataset_events ADD COLUMN IF NOT EXISTS available_tools JSONB DEFAULT '[]'::jsonb;
        ALTER TABLE training_dataset_events ADD COLUMN IF NOT EXISTS tool_calls JSONB DEFAULT '[]'::jsonb;
        ALTER TABLE training_dataset_events ADD COLUMN IF NOT EXISTS tool_results JSONB DEFAULT '[]'::jsonb;
        ALTER TABLE training_dataset_events ADD COLUMN IF NOT EXISTS backend_actions JSONB DEFAULT '{}'::jsonb;
        CREATE INDEX IF NOT EXISTS idx_training_dataset_events_status ON training_dataset_events(quality_status);
        CREATE INDEX IF NOT EXISTS idx_training_dataset_events_platform_business ON training_dataset_events(platform, business_id);
        CREATE INDEX IF NOT EXISTS idx_training_dataset_events_created_at ON training_dataset_events(created_at DESC);
    `);

    ensured = true;
}

function maskSensitiveText(text) {
    return String(text || '')
        .replace(/[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,}/gi, '[EMAIL]')
        .replace(/(?:\+?88)?01[3-9]\d{8}/g, '[PHONE]')
        .replace(/https?:\/\/\S+/gi, '[URL]')
        .trim();
}

function sanitizeJson(value) {
    if (value == null) return value;
    if (typeof value === 'string') return maskSensitiveText(value);
    if (Array.isArray(value)) return value.map(sanitizeJson);
    if (typeof value === 'object') {
        const output = {};
        for (const [key, item] of Object.entries(value)) output[key] = sanitizeJson(item);
        return output;
    }
    return value;
}

function normalizeHistory(history = []) {
    if (!Array.isArray(history)) return [];

    return history
        .slice(-12)
        .map((item) => ({
            role: item.role || (item.reply_by === 'bot' ? 'assistant' : 'user'),
            content: maskSensitiveText(item.content || item.text || '')
        }))
        .filter((item) => item.content && !shouldSkipText(item.content));
}

function detectLanguage(text) {
    const value = String(text || '');
    const hasBangla = /[\u0980-\u09FF]/.test(value);
    const hasEnglish = /[A-Za-z]/.test(value);
    if (hasBangla && hasEnglish) return 'mixed';
    if (hasBangla) return 'bangla';
    if (hasEnglish) return 'banglish_or_english';
    return 'unknown';
}

function inferIntent(text) {
    const value = String(text || '').toLowerCase();
    if (/price|pricing|cost|dam|daam|দাম|মূল্য|koto|কত/.test(value)) return 'pricing_question';
    if (/demo|দেখতে|dekha|dekhte|trial/.test(value)) return 'demo_request';
    if (/facebook|messenger|fb|page/.test(value)) return 'facebook_integration';
    if (/whatsapp|wpp|wa/.test(value)) return 'whatsapp_integration';
    if (/website|site|web/.test(value)) return 'website_integration';
    if (/product|পণ্য|item|catalog|image|ছবি|photo/.test(value)) return 'product_question';
    if (/hello|hi|hey|assalamu|salam|ভাই|vai/.test(value)) return 'greeting';
    return 'general_sales_question';
}

function buildReasoning({ userMessage, assistantReply, agenticOutput = {} }) {
    const action = agenticOutput.action || 'NONE';
    return {
        intent: inferIntent(userMessage),
        language: detectLanguage(`${userMessage}\n${assistantReply}`),
        selected_action: action,
        product_id: agenticOutput.product_id || null,
        photo_decision: agenticOutput.photo_decision || null,
        has_order_details: Boolean(agenticOutput.order_details),
        item_count: Array.isArray(agenticOutput.items) ? agenticOutput.items.length : 0,
        should_send_image: action === 'SEND_PHOTO' || action === 'SEND_BOTH',
        should_save_order: action === 'save_order' || Boolean(agenticOutput.order_details),
        confidence: 0.8
    };
}

function shouldSkipText(text) {
    const value = String(text || '').trim();
    if (!value) return true;
    if (value.length < 2) return true;
    if (/^no reply$/i.test(value)) return true;
    if (/\[SYSTEM ERROR\]|CRITICAL ERROR|Out of Credits|Bot skipped/i.test(value)) return true;
    if (/[αΓ╛╚═║]{8,}/.test(value)) return true;
    return false;
}

function buildBackendActions(agenticOutput = {}, assistantReply = '') {
    const action = agenticOutput.action || 'NONE';
    return {
        send_text: Boolean(String(assistantReply || '').trim()),
        send_photo: action === 'SEND_PHOTO' || action === 'SEND_BOTH' || (Array.isArray(agenticOutput.image_urls) && agenticOutput.image_urls.length > 0),
        send_video: Array.isArray(agenticOutput.video_urls) && agenticOutput.video_urls.length > 0,
        save_order: action === 'save_order' || Boolean(agenticOutput.order_details),
        multi_item: Array.isArray(agenticOutput.items) && agenticOutput.items.length > 0
    };
}

async function collectTrainingSample({
    platform,
    businessId,
    userId,
    systemPrompt,
    conversationHistory,
    userMessage,
    assistantReply,
    aiResponse,
    availableTools,
    modelUsed,
    sourceMessageId,
    metadata
}) {
    const cleanUserMessage = maskSensitiveText(userMessage);
    const cleanAssistantReply = maskSensitiveText(assistantReply);

    if (shouldSkipText(cleanUserMessage) || shouldSkipText(cleanAssistantReply)) return false;

    await ensureTrainingDatasetTable();

    const trace = aiResponse?.agent_trace || {};
    const agenticOutput = sanitizeJson({
        reply_text: cleanAssistantReply,
        action: aiResponse?.action || 'NONE',
        product_id: aiResponse?.product_id || null,
        image_urls: aiResponse?.image_urls || [],
        video_urls: aiResponse?.video_urls || [],
        photo_decision: aiResponse?.photo_decision || null,
        customer_phone: aiResponse?.customer_phone || null,
        customer_address: aiResponse?.customer_address || null,
        customer_name: aiResponse?.customer_name || null,
        product_name: aiResponse?.product_name || null,
        quantity: aiResponse?.quantity || null,
        price: aiResponse?.price || null,
        order_details: aiResponse?.order_details || null,
        items: aiResponse?.items || []
    });
    const reasoning = buildReasoning({ userMessage: cleanUserMessage, assistantReply: cleanAssistantReply, agenticOutput });

    await query(
        `INSERT INTO training_dataset_events
            (platform, business_id, user_id, system_prompt, conversation_history, user_message, assistant_reply, reasoning, agentic_output, available_tools, tool_calls, tool_results, backend_actions, model_used, source_message_id, metadata)
         VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15,$16)`,
        [
            platform,
            businessId || null,
            userId || null,
            maskSensitiveText(systemPrompt || trace.system_prompt || ''),
            JSON.stringify(normalizeHistory(conversationHistory)),
            cleanUserMessage,
            cleanAssistantReply,
            JSON.stringify(reasoning),
            JSON.stringify(agenticOutput),
            JSON.stringify(sanitizeJson(availableTools || trace.available_tools || [])),
            JSON.stringify(sanitizeJson(trace.tool_calls || [])),
            JSON.stringify(sanitizeJson(trace.tool_results || [])),
            JSON.stringify(buildBackendActions(agenticOutput, cleanAssistantReply)),
            modelUsed || aiResponse?.model || null,
            sourceMessageId || null,
            JSON.stringify(sanitizeJson({ ...(metadata || {}), decision_source: 'backend_agentic_runtime' }))
        ]
    );

    return true;
}

module.exports = {
    collectTrainingSample
};
