const os = require('os');
const crypto = require('crypto');
const { query } = require('./pgClient');

const configCache = new Map();
const CONFIG_CACHE_TTL_MS = 30 * 1000;
let tablesReadyPromise = null;

function safeString(value, max = 2000) {
    if (value == null) return null;
    const text = typeof value === 'string' ? value : JSON.stringify(value);
    return text.length > max ? `${text.slice(0, max)}...[trimmed]` : text;
}

function safeJson(value, maxString = 4000) {
    if (value == null) return null;
    try {
        return JSON.parse(JSON.stringify(value, (key, val) => {
            if (key && /token|secret|password|api_?key/i.test(key)) return '[masked]';
            if (typeof val === 'string') return safeString(val, maxString);
            return val;
        }));
    } catch (_) {
        return { value: safeString(value, maxString) };
    }
}

function maskIdentifier(value) {
    if (!value) return null;
    const text = String(value);
    if (text.length <= 6) return `${text.slice(0, 2)}***`;
    return `${text.slice(0, 3)}***${text.slice(-3)}`;
}

async function ensureTables() {
    if (!tablesReadyPromise) {
        tablesReadyPromise = query(`
        CREATE TABLE IF NOT EXISTS ai_trace_configs (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            page_id TEXT NOT NULL,
            platform TEXT NOT NULL DEFAULT 'all',
            trace_enabled BOOLEAN NOT NULL DEFAULT FALSE,
            trace_level TEXT NOT NULL DEFAULT 'full',
            trace_reason TEXT,
            trace_expires_at TIMESTAMPTZ,
            enabled_by TEXT,
            disabled_by TEXT,
            created_at TIMESTAMPTZ DEFAULT NOW(),
            updated_at TIMESTAMPTZ DEFAULT NOW(),
            UNIQUE(page_id, platform)
        );
        CREATE INDEX IF NOT EXISTS idx_ai_trace_configs_active ON ai_trace_configs(page_id, platform, trace_enabled, trace_expires_at);

        CREATE TABLE IF NOT EXISTS ai_message_traces (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            trace_id TEXT NOT NULL UNIQUE,
            page_id TEXT NOT NULL,
            platform TEXT NOT NULL,
            sender_id TEXT,
            user_message_id TEXT,
            bot_message_id TEXT,
            trace_level TEXT NOT NULL DEFAULT 'full',
            request_started_at TIMESTAMPTZ,
            request_finished_at TIMESTAMPTZ DEFAULT NOW(),
            duration_ms INTEGER,
            model TEXT,
            provider TEXT,
            trace_summary JSONB DEFAULT '{}'::jsonb,
            ai_data JSONB DEFAULT '{}'::jsonb,
            product_data JSONB DEFAULT '{}'::jsonb,
            vision_data JSONB DEFAULT '{}'::jsonb,
            order_data JSONB DEFAULT '{}'::jsonb,
            vps_data JSONB DEFAULT '{}'::jsonb,
            error_data JSONB DEFAULT '{}'::jsonb,
            created_at TIMESTAMPTZ DEFAULT NOW()
        );
        CREATE INDEX IF NOT EXISTS idx_ai_message_traces_page_created ON ai_message_traces(page_id, created_at DESC);
        CREATE INDEX IF NOT EXISTS idx_ai_message_traces_message ON ai_message_traces(user_message_id, bot_message_id);

        CREATE TABLE IF NOT EXISTS ai_message_reports (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            page_id TEXT NOT NULL,
            platform TEXT NOT NULL,
            sender_id TEXT,
            message_id TEXT NOT NULL,
            trace_id TEXT,
            report_type TEXT DEFAULT 'other',
            report_note TEXT,
            status TEXT DEFAULT 'pending',
            root_cause TEXT,
            resolution_note TEXT,
            reported_by TEXT,
            resolved_by TEXT,
            created_at TIMESTAMPTZ DEFAULT NOW(),
            resolved_at TIMESTAMPTZ
        );
        CREATE INDEX IF NOT EXISTS idx_ai_message_reports_status_created ON ai_message_reports(status, created_at DESC);
        CREATE INDEX IF NOT EXISTS idx_ai_message_reports_page_created ON ai_message_reports(page_id, created_at DESC);
    `).catch((error) => {
            tablesReadyPromise = null;
            throw error;
        });
    }
    await tablesReadyPromise;
}

async function getTraceConfig(pageId, platform = 'all') {
    if (!pageId) return null;
    const key = `${pageId}:${platform || 'all'}`;
    const cached = configCache.get(key);
    if (cached && Date.now() - cached.ts < CONFIG_CACHE_TTL_MS) return cached.value;

    try {
        await ensureTables();
        const result = await query(
            `SELECT * FROM ai_trace_configs
             WHERE page_id = $1
               AND platform IN ($2, 'all')
               AND trace_enabled = TRUE
               AND (trace_expires_at IS NULL OR trace_expires_at > NOW())
             ORDER BY CASE WHEN platform = $2 THEN 0 ELSE 1 END, updated_at DESC
             LIMIT 1`,
            [String(pageId), String(platform || 'all')]
        );
        const value = result.rows[0] || null;
        configCache.set(key, { ts: Date.now(), value });
        return value;
    } catch (error) {
        console.warn(`[Diagnostic] config check failed: ${error.message}`);
        return null;
    }
}

async function isTraceEnabled(pageId, platform = 'all') {
    const config = await getTraceConfig(pageId, platform);
    return {
        enabled: Boolean(config),
        level: config?.trace_level || null,
        expires_at: config?.trace_expires_at || null
    };
}

async function startTrace({ pageId, platform, senderId, userMessageId }) {
    const config = await getTraceConfig(pageId, platform);
    if (!config) return null;
    return {
        traceId: crypto.randomUUID ? crypto.randomUUID() : crypto.randomBytes(16).toString('hex'),
        pageId: String(pageId),
        platform: String(platform || 'unknown'),
        senderId: senderId ? String(senderId) : null,
        userMessageId: userMessageId ? String(userMessageId) : null,
        level: config.trace_level || 'full',
        startedAt: Date.now(),
        startedAtIso: new Date().toISOString(),
        reason: config.trace_reason || null,
        startVps: captureVpsSnapshot()
    };
}

function captureVpsSnapshot(extra = {}) {
    const mem = process.memoryUsage();
    const total = os.totalmem();
    const free = os.freemem();
    return {
        loadavg: os.loadavg ? os.loadavg() : [],
        memory: {
            total_mb: Math.round(total / 1024 / 1024),
            free_mb: Math.round(free / 1024 / 1024),
            used_percent: total ? Number((((total - free) / total) * 100).toFixed(2)) : null
        },
        process_memory: {
            rss_mb: Math.round(mem.rss / 1024 / 1024),
            heap_used_mb: Math.round(mem.heapUsed / 1024 / 1024),
            heap_total_mb: Math.round(mem.heapTotal / 1024 / 1024)
        },
        uptime_sec: Math.round(process.uptime()),
        ...extra
    };
}

async function saveTrace(trace, payload = {}) {
    if (!trace) return null;
    try {
        await ensureTables();
        const durationMs = Date.now() - trace.startedAt;
        const level = trace.level || 'full';
        const finalVps = captureVpsSnapshot(payload.vps_data || {});
        const summary = {
            reason: trace.reason,
            sender_masked: maskIdentifier(trace.senderId),
            has_image: Boolean(payload.vision_data?.has_image || payload.vision_data?.image_count),
            action: payload.ai_data?.action || null,
            product_id: payload.product_data?.selected_product_id || payload.ai_data?.product_id || null,
            order_saved: payload.order_data?.order_saved || false,
            fallback_used: payload.ai_data?.fallback_used || false,
            error: payload.error_data?.message || null
        };

        const isLight = level === 'light';
        const aiData = isLight ? {
            action: payload.ai_data?.action || null,
            product_id: payload.ai_data?.product_id || null,
            reply_preview: safeString(payload.ai_data?.reply_final || payload.ai_data?.reply_raw, 500),
            fallback_used: payload.ai_data?.fallback_used || false,
            model: payload.ai_data?.model || null,
            provider: payload.ai_data?.provider || null
        } : payload.ai_data;

        const result = await query(
            `INSERT INTO ai_message_traces
                (trace_id, page_id, platform, sender_id, user_message_id, bot_message_id, trace_level,
                 request_started_at, request_finished_at, duration_ms, model, provider, trace_summary,
                 ai_data, product_data, vision_data, order_data, vps_data, error_data)
             VALUES ($1,$2,$3,$4,$5,$6,$7,$8,NOW(),$9,$10,$11,$12,$13,$14,$15,$16,$17,$18)
             ON CONFLICT (trace_id) DO UPDATE SET
                bot_message_id = EXCLUDED.bot_message_id,
                request_finished_at = EXCLUDED.request_finished_at,
                duration_ms = EXCLUDED.duration_ms,
                trace_summary = EXCLUDED.trace_summary,
                ai_data = EXCLUDED.ai_data,
                product_data = EXCLUDED.product_data,
                vision_data = EXCLUDED.vision_data,
                order_data = EXCLUDED.order_data,
                vps_data = EXCLUDED.vps_data,
                error_data = EXCLUDED.error_data
             RETURNING trace_id`,
            [
                trace.traceId,
                trace.pageId,
                trace.platform,
                trace.senderId,
                trace.userMessageId,
                payload.bot_message_id || null,
                level,
                trace.startedAtIso,
                durationMs,
                payload.ai_data?.model || payload.model || null,
                payload.ai_data?.provider || payload.provider || null,
                safeJson(summary),
                safeJson(aiData, isLight ? 800 : 8000),
                safeJson(payload.product_data || {}, isLight ? 800 : 8000),
                safeJson(payload.vision_data || {}, isLight ? 800 : 8000),
                safeJson(payload.order_data || {}, isLight ? 800 : 8000),
                safeJson({ start: trace.startVps, end: finalVps }, 2000),
                safeJson(payload.error_data || {}, 3000)
            ]
        );
        return result.rows[0]?.trace_id || trace.traceId;
    } catch (error) {
        console.warn(`[Diagnostic] trace save failed: ${error.message}`);
        return null;
    }
}

async function enableTrace({ pageId, platform = 'all', traceLevel = 'full', expiresInHours = 48, reason, admin }) {
    await ensureTables();
    const expiresAt = expiresInHours ? new Date(Date.now() + Number(expiresInHours) * 60 * 60 * 1000) : null;
    const result = await query(
        `INSERT INTO ai_trace_configs (page_id, platform, trace_enabled, trace_level, trace_reason, trace_expires_at, enabled_by, updated_at)
         VALUES ($1,$2,TRUE,$3,$4,$5,$6,NOW())
         ON CONFLICT (page_id, platform) DO UPDATE SET
            trace_enabled = TRUE,
            trace_level = EXCLUDED.trace_level,
            trace_reason = EXCLUDED.trace_reason,
            trace_expires_at = EXCLUDED.trace_expires_at,
            enabled_by = EXCLUDED.enabled_by,
            disabled_by = NULL,
            updated_at = NOW()
         RETURNING *`,
        [String(pageId), String(platform || 'all'), String(traceLevel || 'full'), reason || null, expiresAt, admin || null]
    );
    configCache.clear();
    return result.rows[0];
}

async function disableTrace({ pageId, platform = 'all', admin }) {
    await ensureTables();
    const result = await query(
        `UPDATE ai_trace_configs
         SET trace_enabled = FALSE, disabled_by = $3, updated_at = NOW()
         WHERE page_id = $1 AND platform = $2
         RETURNING *`,
        [String(pageId), String(platform || 'all'), admin || null]
    );
    configCache.clear();
    return result.rows[0] || null;
}

async function deleteTraceConfig({ pageId, platform = 'all' }) {
    if (!pageId) {
        const error = new Error('page_id is required');
        error.statusCode = 400;
        throw error;
    }

    await ensureTables();
    const page = String(pageId);
    const configPlatform = String(platform || 'all');
    const reportPlatformFilter = configPlatform === 'all' ? '' : 'AND platform = $2';
    const reportParams = configPlatform === 'all' ? [page] : [page, configPlatform];

    const reportsResult = await query(
        `DELETE FROM ai_message_reports WHERE page_id = $1 ${reportPlatformFilter} RETURNING id, trace_id`,
        reportParams
    );
    const traceIds = reportsResult.rows.map(row => row.trace_id).filter(Boolean);

    if (traceIds.length) {
        await query('DELETE FROM ai_message_traces WHERE trace_id = ANY($1)', [traceIds]);
    }

    await query(
        `DELETE FROM ai_message_traces WHERE page_id = $1 ${reportPlatformFilter}`,
        reportParams
    );

    const configResult = await query(
        'DELETE FROM ai_trace_configs WHERE page_id = $1 AND platform = $2 RETURNING *',
        [page, configPlatform]
    );

    configCache.clear();
    return {
        config: configResult.rows[0] || null,
        deleted_reports: reportsResult.rowCount || 0,
        deleted_trace_ids: traceIds.length
    };
}

async function listTraceConfigs() {
    await ensureTables();
    const result = await query('SELECT * FROM ai_trace_configs ORDER BY trace_enabled DESC, updated_at DESC LIMIT 200');
    return result.rows;
}

async function listReports({ status, pageId, platform, limit = 100 } = {}) {
    await ensureTables();
    const params = [];
    const where = [];
    if (status) { params.push(status); where.push(`r.status = $${params.length}`); }
    if (pageId) { params.push(String(pageId)); where.push(`r.page_id = $${params.length}`); }
    if (platform && platform !== 'all') { params.push(String(platform)); where.push(`r.platform = $${params.length}`); }
    params.push(Math.min(Number(limit) || 100, 300));
    const result = await query(
        `SELECT r.*, t.trace_summary, t.created_at AS trace_created_at
         FROM ai_message_reports r
         LEFT JOIN ai_message_traces t ON t.trace_id = r.trace_id
         ${where.length ? `WHERE ${where.join(' AND ')}` : ''}
         ORDER BY r.created_at DESC
         LIMIT $${params.length}`,
        params
    );
    return result.rows;
}

async function getReport(reportId) {
    await ensureTables();
    const result = await query(
        `SELECT r.*, row_to_json(t.*) AS trace
         FROM ai_message_reports r
         LEFT JOIN ai_message_traces t ON t.trace_id = r.trace_id
         WHERE r.id = $1 LIMIT 1`,
        [reportId]
    );
    return result.rows[0] || null;
}

async function getTrace(traceId) {
    await ensureTables();
    const result = await query('SELECT * FROM ai_message_traces WHERE trace_id = $1 LIMIT 1', [traceId]);
    return result.rows[0] || null;
}

async function reportMessage({ pageId, platform, senderId, messageId, reportType, note, reportedBy }) {
    if (!pageId || !platform || !messageId) {
        const error = new Error('page_id, platform and message_id are required');
        error.statusCode = 400;
        throw error;
    }

    const status = await isTraceEnabled(pageId, platform);
    if (!status.enabled) {
        const error = new Error('Diagnostic mode is not enabled for this page/platform');
        error.statusCode = 403;
        throw error;
    }

    await ensureTables();
    const traceResult = await query(
        `SELECT trace_id FROM ai_message_traces
         WHERE page_id = $1 AND platform = $2 AND (bot_message_id = $3 OR user_message_id = $3)
         ORDER BY created_at DESC LIMIT 1`,
        [String(pageId), String(platform || 'unknown'), String(messageId)]
    );
    const traceId = traceResult.rows[0]?.trace_id || null;
    const result = await query(
        `INSERT INTO ai_message_reports (page_id, platform, sender_id, message_id, trace_id, report_type, report_note, reported_by)
         VALUES ($1,$2,$3,$4,$5,$6,$7,$8)
         RETURNING *`,
        [String(pageId), String(platform || 'unknown'), senderId || null, String(messageId), traceId, reportType || 'other', note || null, reportedBy || null]
    );
    return result.rows[0];
}

async function updateReportStatus({ reportId, status, rootCause, resolutionNote, resolvedBy }) {
    await ensureTables();
    const result = await query(
        `UPDATE ai_message_reports
         SET status = COALESCE($2, status),
             root_cause = COALESCE($3, root_cause),
             resolution_note = COALESCE($4, resolution_note),
             resolved_by = COALESCE($5, resolved_by),
             resolved_at = CASE WHEN $2 IN ('fixed','closed','ignored') THEN NOW() ELSE resolved_at END
         WHERE id = $1
         RETURNING *`,
        [reportId, status || null, rootCause || null, resolutionNote || null, resolvedBy || null]
    );
    return result.rows[0] || null;
}

module.exports = {
    isTraceEnabled,
    startTrace,
    saveTrace,
    captureVpsSnapshot,
    enableTrace,
    disableTrace,
    deleteTraceConfig,
    listTraceConfigs,
    listReports,
    getReport,
    getTrace,
    reportMessage,
    updateReportStatus
};
