const dbService = require('../services/dbService');
const aiService = require('../services/aiService');
const commentAutomationService = require('../services/commentAutomationService');
const instagramService = require('../services/instagramService');
const pgClient = require('../services/pgClient');
const fs = require('fs');
const path = require('path');

// #region debug-point ads-product-routing:reporter
function reportAdsProductRoutingDebug(hypothesisId, location, msg, data = {}) {
    try {
        const envPath = path.join(__dirname, '../../.dbg/ads-product-routing.env');
        let debugUrl = 'http://127.0.0.1:7777/event';
        let sessionId = 'ads-product-routing';
        try {
            const envContent = fs.readFileSync(envPath, 'utf8');
            debugUrl = envContent.match(/DEBUG_SERVER_URL=(.+)/)?.[1]?.trim() || debugUrl;
            sessionId = envContent.match(/DEBUG_SESSION_ID=(.+)/)?.[1]?.trim() || sessionId;
        } catch (_) {}
        fetch(debugUrl, {
            method: 'POST',
            headers: { 'Content-Type': 'application/json' },
            body: JSON.stringify({ sessionId, runId: 'pre-fix', hypothesisId, location, msg: `[DEBUG] ${msg}`, data, ts: Date.now() })
        }).catch(() => {});
    } catch (_) {}
}
// #endregion

const recentInstagramWebhookLogs = [];
const MAX_INSTAGRAM_WEBHOOK_LOGS = 50;

function addInstagramWebhookLog(payload) {
    recentInstagramWebhookLogs.unshift({
        id: Date.now() + Math.random().toString(36).slice(2, 7),
        timestamp: new Date().toISOString(),
        object: payload?.object,
        sourceId: String(payload?.entry?.[0]?.id || 'unknown'),
        entry_count: Array.isArray(payload?.entry) ? payload.entry.length : 0,
        payload
    });
    if (recentInstagramWebhookLogs.length > MAX_INSTAGRAM_WEBHOOK_LOGS) recentInstagramWebhookLogs.pop();
}

function getInstagramWebhookLogs(req, res) {
    const sourceId = req.query.sourceId ? String(req.query.sourceId) : '';
    const logs = sourceId ? recentInstagramWebhookLogs.filter(log => log.sourceId === sourceId) : recentInstagramWebhookLogs;
    res.json({ logs });
}

function verifyInstagramWebhook(req, res) {
    const token = req.query['hub.verify_token'];
    const expected = new Set([
        process.env.INSTAGRAM_VERIFY_TOKEN,
        process.env.FACEBOOK_VERIFY_TOKEN,
        process.env.VERIFY_TOKEN,
        '123456'
    ].filter(Boolean));
    if (req.query['hub.mode'] === 'subscribe' && expected.has(token)) {
        return res.status(200).send(req.query['hub.challenge']);
    }
    return res.sendStatus(403);
}

async function ensureInstagramRuntimeTables() {
    await pgClient.query(`
        CREATE TABLE IF NOT EXISTS instagram_accounts (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            instagram_account_id TEXT NOT NULL,
            instagram_username TEXT,
            name TEXT,
            facebook_page_id TEXT,
            page_access_token TEXT,
            user_access_token TEXT,
            email TEXT,
            user_id TEXT,
            ai TEXT DEFAULT 'gemini',
            chat_model TEXT DEFAULT 'gemini-2.0-flash',
            cheap_engine BOOLEAN DEFAULT TRUE,
            subscription_status TEXT DEFAULT 'active',
            created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
            updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
            UNIQUE(user_id, instagram_account_id)
        );

        CREATE TABLE IF NOT EXISTS instagram_message_database (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            instagram_account_id TEXT NOT NULL UNIQUE,
            user_id TEXT,
            text_prompt TEXT,
            wait INTEGER DEFAULT 5,
            image_send BOOLEAN DEFAULT TRUE,
            image_detection BOOLEAN DEFAULT TRUE,
            template BOOLEAN DEFAULT TRUE,
            reply_message BOOLEAN DEFAULT TRUE,
            order_tracking BOOLEAN DEFAULT TRUE,
            swipe_reply BOOLEAN DEFAULT FALSE,
            audio_detection BOOLEAN DEFAULT FALSE,
            block_emoji TEXT DEFAULT '',
            unblock_emoji TEXT DEFAULT '',
            image_prompt TEXT DEFAULT '',
            check_conversion INTEGER DEFAULT 20,
            temperature NUMERIC DEFAULT 0.7,
            top_p NUMERIC DEFAULT 0.9,
            ai TEXT,
            api_key TEXT,
            chat_model TEXT,
            created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
            updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
        );
    `);
}

async function getInstagramConfig(accountId) {
    await ensureInstagramRuntimeTables();
    const result = await pgClient.query(`
        SELECT a.*, d.*,
               a.id AS token_row_id, d.id AS config_id,
               a.instagram_account_id AS page_id,
               COALESCE(d.ai, a.ai) AS ai,
               COALESCE(d.chat_model, a.chat_model) AS chat_model
        FROM instagram_accounts a
        LEFT JOIN instagram_message_database d ON d.instagram_account_id = a.instagram_account_id
        WHERE a.instagram_account_id = $1
        LIMIT 1`, [String(accountId)]);
    return result.rows[0] || null;
}

function normalizeAttachments(message) {
    return (message.attachments || [])
        .map((attachment) => attachment.payload?.url || attachment.payload?.src)
        .filter(Boolean);
}

async function processInstagramWebhook(body) {
    for (const entry of body.entry || []) {
        const accountId = String(entry.id || '');
        if (!accountId) continue;
        const config = await getInstagramConfig(accountId);
        if (!config?.page_access_token) continue;

        for (const change of entry.changes || []) {
            if (!['comments', 'feed'].includes(change.field)) continue;
            const value = change.value || {};
            const commentId = value.comment_id || value.id;
            const commenterId = value.from?.id || value.user_id;
            const postId = value.media?.id || value.media_id || value.post_id;
            const commentText = value.text || value.message || '';
            if (!commentId || !commenterId || !postId || String(commenterId) === accountId) continue;
            await commentAutomationService.processCommentAutomationEvent({
                platform: 'instagram',
                accountId,
                postId,
                commentId,
                commenterId,
                commentText,
                accessToken: config.page_access_token,
                accountConfig: config
            });
        }

        for (const event of entry.messaging || []) {
            if (event.message?.is_echo || !event.sender?.id || !event.message) continue;
            const senderId = String(event.sender.id);
            const messageId = String(event.message.mid || `instagram_${Date.now()}_${senderId}`);
            const text = String(event.message.text || '').trim();
            // #region debug-point ads-product-routing:instagram-incoming
            reportAdsProductRoutingDebug('H4', 'instagramController.js:processInstagramWebhook.incoming', 'instagram incoming payload ad/referral fields', {
                accountId,
                senderId,
                messageId,
                textPreview: text.substring(0, 500),
                referral: event.referral || event.postback?.referral || event.message?.referral || null,
                eventKeys: Object.keys(event || {}).filter(k => /ref|ad|source|context/i.test(k)),
                messageKeys: Object.keys(event.message || {}).filter(k => /ref|ad|source|context/i.test(k))
            });
            // #endregion
            const imageUrls = normalizeAttachments(event.message);
            if (!text && !imageUrls.length) continue;

            const bodyText = [text, ...imageUrls.map((url) => `[Image URL]: ${url}`)].filter(Boolean).join('\n');
            await dbService.saveInstagramChat({
                instagram_account_id: accountId,
                sender_id: senderId,
                recipient_id: accountId,
                message_id: messageId,
                text: bodyText,
                timestamp: Number(event.timestamp) || Date.now(),
                status: 'received',
                reply_by: 'user'
            });

            if (!text && imageUrls.length && !config.image_detection) continue;
            const history = await dbService.getInstagramChatHistory(accountId, senderId, 12);
            // #region debug-point ads-product-routing:instagram-final-ai-context
            reportAdsProductRoutingDebug('H4', 'instagramController.js:processInstagramWebhook.finalContext', 'instagram final AI context before generation', {
                accountId,
                senderId,
                messageId,
                userMessagePreview: String(text || 'The customer sent an image.').substring(0, 1500),
                imageCount: imageUrls.length,
                hasConfig: Boolean(config)
            });
            // #endregion
            const result = await aiService.generateResponse({
                pageId: accountId,
                userId: senderId,
                userMessage: text || 'The customer sent an image.',
                history,
                imageUrls,
                audioUrls: [],
                config,
                platform: 'instagram'
            });
            const reply = typeof result === 'string' ? result : (result?.reply || result?.reply_text || '');
            if (!reply) continue;

            const sent = await instagramService.sendMessage(accountId, senderId, reply, config.page_access_token);
            await dbService.saveInstagramChat({
                instagram_account_id: accountId,
                sender_id: accountId,
                recipient_id: senderId,
                message_id: String(sent?.message_id || `instagram_bot_${Date.now()}`),
                text: reply,
                timestamp: Date.now(),
                status: 'sent',
                reply_by: 'bot',
                token: Number(result?.token || result?.tokens || 0),
                ai_model: result?.model || result?.ai_model || config.chat_model
            });
        }
    }
}

async function handleInstagramWebhook(req, res) {
    addInstagramWebhookLog(req.body);
    res.status(200).send('EVENT_RECEIVED');
    if (req.body?.object !== 'instagram') return;
    processInstagramWebhook(req.body).catch((error) => {
        console.error('[Instagram Webhook] Background processing failed:', error.message);
    });
}

module.exports = { verifyInstagramWebhook, handleInstagramWebhook, processInstagramWebhook, getInstagramWebhookLogs };
