const express = require('express');
const crypto = require('crypto');
const axios = require('axios');
const pgClient = require('../services/pgClient');
const authMiddleware = require('../middleware/authMiddleware');

const router = express.Router();
const STEADFAST_BASE_URL = process.env.STEADFAST_BASE_URL || 'https://portal.packzy.com/api/v1';
const SUPPORTED_PROVIDERS = ['steadfast', 'pathao', 'redx'];

function normalizeProvider(provider) {
    const value = String(provider || '').trim().toLowerCase();
    return SUPPORTED_PROVIDERS.includes(value) ? value : 'steadfast';
}

function getCipherKey() {
    const secret = process.env.COURIER_ENCRYPTION_KEY || process.env.JWT_SECRET || process.env.DATABASE_URL || 'salesmanai-courier-local-key';
    return crypto.createHash('sha256').update(String(secret)).digest();
}

function encrypt(value) {
    if (!value) return null;
    const iv = crypto.randomBytes(12);
    const cipher = crypto.createCipheriv('aes-256-gcm', getCipherKey(), iv);
    const encrypted = Buffer.concat([cipher.update(String(value), 'utf8'), cipher.final()]);
    const tag = cipher.getAuthTag();
    return `${iv.toString('base64')}:${tag.toString('base64')}:${encrypted.toString('base64')}`;
}

function decrypt(value) {
    if (!value) return '';
    const [ivText, tagText, encryptedText] = String(value).split(':');
    const decipher = crypto.createDecipheriv('aes-256-gcm', getCipherKey(), Buffer.from(ivText, 'base64'));
    decipher.setAuthTag(Buffer.from(tagText, 'base64'));
    return Buffer.concat([decipher.update(Buffer.from(encryptedText, 'base64')), decipher.final()]).toString('utf8');
}

function maskSecret(value) {
    if (!value) return null;
    const text = String(value);
    if (text.length <= 8) return '••••••••';
    return `${text.slice(0, 4)}••••${text.slice(-4)}`;
}

async function ensureCourierTables() {
    await pgClient.query(`
        CREATE TABLE IF NOT EXISTS courier_settings (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            user_id TEXT NOT NULL,
            user_email TEXT,
            provider TEXT NOT NULL DEFAULT 'steadfast',
            api_key_encrypted TEXT,
            secret_key_encrypted TEXT,
            merchant_id_encrypted TEXT,
            store_id_encrypted TEXT,
            pickup_address TEXT,
            is_active BOOLEAN DEFAULT TRUE,
            last_tested_at TIMESTAMP WITH TIME ZONE,
            created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
            updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
            UNIQUE(user_id, provider)
        );

        CREATE TABLE IF NOT EXISTS courier_shipments (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            user_id TEXT NOT NULL,
            user_email TEXT,
            provider TEXT NOT NULL,
            platform TEXT NOT NULL,
            order_id TEXT NOT NULL,
            tracking_code TEXT,
            consignment_id TEXT,
            invoice TEXT,
            courier_status TEXT,
            request_payload JSONB,
            response_payload JSONB,
            error_message TEXT,
            created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
            updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
            UNIQUE(provider, platform, order_id)
        );

        ALTER TABLE courier_settings ADD COLUMN IF NOT EXISTS merchant_id_encrypted TEXT;
        ALTER TABLE courier_settings ADD COLUMN IF NOT EXISTS store_id_encrypted TEXT;

        ALTER TABLE IF EXISTS whatsapp_order_tracking ADD COLUMN IF NOT EXISTS courier_provider TEXT;
        ALTER TABLE IF EXISTS whatsapp_order_tracking ADD COLUMN IF NOT EXISTS courier_tracking_code TEXT;
        ALTER TABLE IF EXISTS whatsapp_order_tracking ADD COLUMN IF NOT EXISTS courier_status TEXT;
        ALTER TABLE IF EXISTS fb_order_tracking ADD COLUMN IF NOT EXISTS courier_provider TEXT;
        ALTER TABLE IF EXISTS fb_order_tracking ADD COLUMN IF NOT EXISTS courier_tracking_code TEXT;
        ALTER TABLE IF EXISTS fb_order_tracking ADD COLUMN IF NOT EXISTS courier_status TEXT;
        ALTER TABLE IF EXISTS instagram_order_tracking ADD COLUMN IF NOT EXISTS courier_provider TEXT;
        ALTER TABLE IF EXISTS instagram_order_tracking ADD COLUMN IF NOT EXISTS courier_tracking_code TEXT;
        ALTER TABLE IF EXISTS instagram_order_tracking ADD COLUMN IF NOT EXISTS courier_status TEXT;
    `);
}

function toPublicSettings(row) {
    if (!row) return { connected: false, provider: 'steadfast', is_active: false };
    let apiKey = '';
    let secretKey = '';
    let merchantId = '';
    let storeId = '';
    try {
        apiKey = decrypt(row.api_key_encrypted);
        secretKey = decrypt(row.secret_key_encrypted);
        merchantId = decrypt(row.merchant_id_encrypted);
        storeId = decrypt(row.store_id_encrypted);
    } catch (_) {}
    return {
        connected: Boolean(row.api_key_encrypted && row.secret_key_encrypted && row.is_active),
        provider: row.provider,
        api_key_masked: maskSecret(apiKey),
        secret_key_masked: maskSecret(secretKey),
        merchant_id_masked: maskSecret(merchantId),
        store_id_masked: maskSecret(storeId),
        pickup_address: row.pickup_address || '',
        is_active: Boolean(row.is_active),
        last_tested_at: row.last_tested_at,
        updated_at: row.updated_at,
    };
}

async function getSettings(userId, provider = 'steadfast') {
    await ensureCourierTables();
    const { rows } = await pgClient.query(
        `SELECT * FROM courier_settings WHERE user_id::text = $1::text AND provider = $2 LIMIT 1`,
        [String(userId), provider]
    );
    return rows[0] || null;
}

async function getActiveSettings(userId, provider) {
    if (provider) return getSettings(userId, normalizeProvider(provider));
    await ensureCourierTables();
    const { rows } = await pgClient.query(
        `SELECT * FROM courier_settings
         WHERE user_id::text = $1::text AND is_active = TRUE
         ORDER BY updated_at DESC
         LIMIT 1`,
        [String(userId)]
    );
    return rows[0] || null;
}

async function getActiveCredentials(userId, provider) {
    const settings = await getActiveSettings(userId, provider);
    if (!settings || !settings.is_active || !settings.api_key_encrypted || !settings.secret_key_encrypted) return null;
    return {
        ...settings,
        apiKey: decrypt(settings.api_key_encrypted),
        secretKey: decrypt(settings.secret_key_encrypted),
        merchantId: decrypt(settings.merchant_id_encrypted),
        storeId: decrypt(settings.store_id_encrypted),
    };
}

function getSteadfastHeaders(credentials) {
    return {
        'Api-Key': credentials.apiKey,
        'Secret-Key': credentials.secretKey,
        'Content-Type': 'application/json',
    };
}

async function testCourier(credentials) {
    if (credentials.provider === 'steadfast') {
        const response = await axios.get(`${STEADFAST_BASE_URL}/get_balance`, {
            headers: getSteadfastHeaders(credentials),
            timeout: 15000,
        });
        return response.data;
    }

    return {
        message: `${credentials.provider} credentials saved. Live test endpoint is not configured yet.`,
        configured: true,
    };
}

async function createCourierOrder(provider, credentials, payload) {
    if (provider === 'steadfast') {
        const response = await axios.post(`${STEADFAST_BASE_URL}/create_order`, payload, {
            headers: getSteadfastHeaders(credentials),
            timeout: 20000,
        });
        return response.data || {};
    }

    throw new Error(`${provider} live booking endpoint is not configured yet`);
}

function normalizeMoney(value) {
    const amount = Number(String(value || '').replace(/[^0-9.]/g, ''));
    return Number.isFinite(amount) && amount > 0 ? amount : 0;
}

function normalizeOrderPayload(order) {
    return {
        invoice: `SA-${order.id}-${Date.now()}`.slice(0, 80),
        recipient_name: order.customer_name || 'Customer',
        recipient_phone: order.number,
        recipient_address: order.location,
        cod_amount: normalizeMoney(order.price),
        note: [order.product_name, order.product_quantity ? `Qty: ${order.product_quantity}` : null].filter(Boolean).join(' | '),
    };
}

async function loadAuthorizedOrder(userId, userEmail, platform, orderId) {
    const id = String(orderId || '').trim();
    if (!id) return null;

    if (platform === 'whatsapp') {
        const { rows } = await pgClient.query(
            `SELECT o.*
             FROM whatsapp_order_tracking o
             JOIN whatsapp_message_database w ON w.session_name = o.session_name
             WHERE o.id = $1
               AND (w.user_id::text = $2::text OR LOWER(w.email) = LOWER($3))
             LIMIT 1`,
            [id, String(userId || ''), String(userEmail || '')]
        );
        return rows[0] || null;
    }

    if (platform === 'messenger') {
        const { rows } = await pgClient.query(
            `SELECT o.*
             FROM fb_order_tracking o
             JOIN page_access_token_message p ON p.page_id = o.page_id
             WHERE o.id = $1
               AND (p.user_id::text = $2::text OR LOWER(p.email) = LOWER($3))
             LIMIT 1`,
            [id, String(userId || ''), String(userEmail || '')]
        );
        return rows[0] || null;
    }

    if (platform === 'instagram') {
        const { rows } = await pgClient.query(
            `SELECT o.*
             FROM instagram_order_tracking o
             JOIN instagram_accounts a ON a.instagram_account_id = o.instagram_account_id
             WHERE o.id = $1
               AND (a.user_id::text = $2::text OR LOWER(a.email) = LOWER($3))
             LIMIT 1`,
            [id, String(userId || ''), String(userEmail || '')]
        );
        return rows[0] || null;
    }

    return null;
}

async function markOrderShipped(platform, orderId, provider, trackingCode, courierStatus) {
    const table = platform === 'whatsapp'
        ? 'whatsapp_order_tracking'
        : platform === 'messenger'
            ? 'fb_order_tracking'
            : 'instagram_order_tracking';
    await pgClient.query(
        `UPDATE ${table}
         SET courier_provider = $1, courier_tracking_code = $2, courier_status = $3, updated_at = NOW()
         WHERE id = $4`,
        [provider, trackingCode || null, courierStatus || 'booked', orderId]
    );
}

async function createShipment({ req, platform, provider, order }) {
    const credentials = await getActiveCredentials(req.user.id, provider);
    const activeProvider = credentials?.provider || normalizeProvider(provider);
    if (!credentials) {
        const error = new Error('Courier API is not connected yet');
        error.statusCode = 404;
        throw error;
    }

    const dbOrder = await loadAuthorizedOrder(req.user.id, req.user.email, platform, order?.id);
    if (!dbOrder) {
        const error = new Error('Order not found');
        error.statusCode = 404;
        throw error;
    }
    if (!dbOrder.number || !dbOrder.location) {
        const error = new Error('Phone and address are required before sending to courier');
        error.statusCode = 400;
        throw error;
    }

    const payload = normalizeOrderPayload(dbOrder);
    let courierResponse;
    try {
        courierResponse = await createCourierOrder(activeProvider, credentials, payload);
    } catch (error) {
        const message = error.response?.data?.message || error.response?.data?.error || error.message || 'Courier booking failed';
        await pgClient.query(
            `INSERT INTO courier_shipments (user_id, user_email, provider, platform, order_id, invoice, request_payload, response_payload, error_message, courier_status)
             VALUES ($1, $2, $3, $4, $5, $6, $7::jsonb, $8::jsonb, $9, $10)
             ON CONFLICT (provider, platform, order_id)
             DO UPDATE SET request_payload = EXCLUDED.request_payload, response_payload = EXCLUDED.response_payload, error_message = EXCLUDED.error_message, courier_status = EXCLUDED.courier_status, updated_at = NOW()`,
            [String(req.user.id), req.user.email || null, activeProvider, platform, String(dbOrder.id), payload.invoice, JSON.stringify(payload), JSON.stringify(error.response?.data || {}), message, 'failed']
        );
        const err = new Error(message);
        err.statusCode = error.response?.status || 502;
        throw err;
    }

    const data = courierResponse.consignment || courierResponse.data || courierResponse;
    const trackingCode = data.tracking_code || data.consignment_id || data.cn || data.invoice || null;
    const consignmentId = data.consignment_id || data.id || null;
    const courierStatus = data.status || courierResponse.status || 'booked';

    await pgClient.query(
        `INSERT INTO courier_shipments (user_id, user_email, provider, platform, order_id, tracking_code, consignment_id, invoice, courier_status, request_payload, response_payload)
         VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10::jsonb, $11::jsonb)
         ON CONFLICT (provider, platform, order_id)
         DO UPDATE SET tracking_code = EXCLUDED.tracking_code, consignment_id = EXCLUDED.consignment_id, invoice = EXCLUDED.invoice, courier_status = EXCLUDED.courier_status, request_payload = EXCLUDED.request_payload, response_payload = EXCLUDED.response_payload, error_message = NULL, updated_at = NOW()
         RETURNING *`,
        [String(req.user.id), req.user.email || null, activeProvider, platform, String(dbOrder.id), trackingCode, consignmentId, payload.invoice, courierStatus, JSON.stringify(payload), JSON.stringify(courierResponse)]
    );

    await markOrderShipped(platform, dbOrder.id, activeProvider, trackingCode, courierStatus);
    return { success: true, provider: activeProvider, tracking_code: trackingCode, consignment_id: consignmentId, status: courierStatus, response: courierResponse };
}

router.get('/settings', authMiddleware, async (req, res) => {
    try {
        const provider = normalizeProvider(req.query.provider || 'steadfast');
        const settings = await getSettings(req.user.id, provider);
        res.json(toPublicSettings(settings));
    } catch (error) {
        console.error('Courier settings load error:', error);
        res.status(500).json({ error: error.message });
    }
});

router.post('/settings', authMiddleware, async (req, res) => {
    try {
        await ensureCourierTables();
        const provider = normalizeProvider(req.body?.provider || 'steadfast');

        const existing = await getSettings(req.user.id, provider);
        const apiKey = String(req.body?.api_key || '').trim();
        const secretKey = String(req.body?.secret_key || '').trim();
        const merchantId = String(req.body?.merchant_id || '').trim();
        const storeId = String(req.body?.store_id || '').trim();
        const apiKeyEncrypted = apiKey ? encrypt(apiKey) : existing?.api_key_encrypted || null;
        const secretKeyEncrypted = secretKey ? encrypt(secretKey) : existing?.secret_key_encrypted || null;
        const merchantIdEncrypted = merchantId ? encrypt(merchantId) : existing?.merchant_id_encrypted || null;
        const storeIdEncrypted = storeId ? encrypt(storeId) : existing?.store_id_encrypted || null;
        const pickupAddress = String(req.body?.pickup_address || '').trim();
        const isActive = req.body?.is_active !== false;

        if (!apiKeyEncrypted || !secretKeyEncrypted) {
            return res.status(400).json({ error: 'API key and secret key are required' });
        }

        if (isActive) {
            await pgClient.query(
                `UPDATE courier_settings SET is_active = FALSE, updated_at = NOW() WHERE user_id::text = $1::text AND provider <> $2`,
                [String(req.user.id), provider]
            );
        }

        const { rows } = await pgClient.query(
            `INSERT INTO courier_settings (user_id, user_email, provider, api_key_encrypted, secret_key_encrypted, merchant_id_encrypted, store_id_encrypted, pickup_address, is_active)
             VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
             ON CONFLICT (user_id, provider)
             DO UPDATE SET user_email = EXCLUDED.user_email, api_key_encrypted = EXCLUDED.api_key_encrypted, secret_key_encrypted = EXCLUDED.secret_key_encrypted, merchant_id_encrypted = EXCLUDED.merchant_id_encrypted, store_id_encrypted = EXCLUDED.store_id_encrypted, pickup_address = EXCLUDED.pickup_address, is_active = EXCLUDED.is_active, updated_at = NOW()
             RETURNING *`,
            [String(req.user.id), req.user.email || null, provider, apiKeyEncrypted, secretKeyEncrypted, merchantIdEncrypted, storeIdEncrypted, pickupAddress, isActive]
        );

        res.json({ success: true, settings: toPublicSettings(rows[0]) });
    } catch (error) {
        console.error('Courier settings save error:', error);
        res.status(500).json({ error: error.message });
    }
});

router.post('/test', authMiddleware, async (req, res) => {
    try {
        const provider = normalizeProvider(req.body?.provider || 'steadfast');
        const credentials = await getActiveCredentials(req.user.id, provider);
        if (!credentials) return res.status(404).json({ error: 'Courier API is not connected yet' });
        const data = await testCourier(credentials);
        await pgClient.query(
            `UPDATE courier_settings SET last_tested_at = NOW(), updated_at = NOW() WHERE user_id::text = $1::text AND provider = $2`,
            [String(req.user.id), provider]
        );
        res.json({ success: true, data });
    } catch (error) {
        const message = error.response?.data?.message || error.response?.data?.error || error.message || 'Courier test failed';
        res.status(error.response?.status || 502).json({ error: message });
    }
});

router.post('/shipments', authMiddleware, async (req, res) => {
    try {
        await ensureCourierTables();
        const platform = String(req.body?.platform || '').trim().toLowerCase();
        const provider = req.body?.provider ? normalizeProvider(req.body.provider) : null;
        if (!['whatsapp', 'messenger', 'instagram'].includes(platform)) return res.status(400).json({ error: 'Invalid platform' });
        const result = await createShipment({ req, platform, provider, order: req.body?.order });
        res.json(result);
    } catch (error) {
        res.status(error.statusCode || 500).json({ error: error.message });
    }
});

router.post('/shipments/bulk', authMiddleware, async (req, res) => {
    try {
        await ensureCourierTables();
        const platform = String(req.body?.platform || '').trim().toLowerCase();
        const provider = req.body?.provider ? normalizeProvider(req.body.provider) : null;
        const orders = Array.isArray(req.body?.orders) ? req.body.orders : [];
        if (!['whatsapp', 'messenger', 'instagram'].includes(platform)) return res.status(400).json({ error: 'Invalid platform' });
        if (!orders.length) return res.status(400).json({ error: 'No orders selected' });

        const results = [];
        for (const order of orders) {
            try {
                results.push({ order_id: order?.id, ...(await createShipment({ req, platform, provider, order })) });
            } catch (error) {
                results.push({ order_id: order?.id, success: false, error: error.message });
            }
        }

        res.json({
            success: true,
            total: results.length,
            sent: results.filter((item) => item.success).length,
            failed: results.filter((item) => !item.success).length,
            results,
        });
    } catch (error) {
        res.status(error.statusCode || 500).json({ error: error.message });
    }
});

module.exports = router;
