const express = require('express');
const multer = require('multer');
const router = express.Router();
const axios = require('axios');
const pgClient = require('../services/pgClient');
const dbService = require('../services/dbService');
const imageService = require('../services/imageService');
const facebookService = require('../services/facebookService');
const authMiddleware = require('../middleware/authMiddleware');
const instagramController = require('../controllers/instagramController');
const { getSmartInboxConversations, upsertSmartInboxLabel } = require('../utils/smartInbox');

const GRAPH_VERSION = process.env.FACEBOOK_GRAPH_VERSION || 'v25.0';
const upload = multer({ storage: multer.memoryStorage(), limits: { fileSize: 16 * 1024 * 1024 }, fileFilter: (req, file, cb) => cb(null, file.mimetype?.startsWith('image/')) });

async function ensureInstagramColumns() {
    await pgClient.query(`ALTER TABLE page_access_token_message ADD COLUMN IF NOT EXISTS platform text NOT NULL DEFAULT 'messenger'`);
    await pgClient.query(`ALTER TABLE fb_message_database ADD COLUMN IF NOT EXISTS platform text NOT NULL DEFAULT 'messenger'`);
}
const getAccount = async (accountId, userId) => {
    await ensureInstagramColumns();
    const { rows } = await pgClient.query(`SELECT p.*, d.id AS db_id FROM page_access_token_message p LEFT JOIN fb_message_database d ON d.page_id=p.page_id AND d.platform='instagram' WHERE p.page_id=$1 AND p.platform='instagram' AND p.user_id::text=$2 LIMIT 1`, [String(accountId), String(userId)]);
    return rows[0] || null;
};
router.get('/webhook', instagramController.verifyInstagramWebhook);
router.post('/webhook', instagramController.handleInstagramWebhook);
router.get('/pages', authMiddleware, async (req, res) => {
    try { await ensureInstagramColumns(); const { rows } = await pgClient.query(`SELECT p.page_id,p.name,p.id,d.id AS db_id FROM page_access_token_message p LEFT JOIN fb_message_database d ON d.page_id=p.page_id AND d.platform='instagram' WHERE p.platform='instagram' AND p.user_id::text=$1 ORDER BY p.id DESC`, [String(req.user.id)]); res.json(rows); } catch (e) { res.status(500).json({ error: e.message }); }
});
router.post('/pages/manual', authMiddleware, async (req, res) => {
    try { const { page_id, name, page_access_token } = req.body || {}; if (!page_id || !name || !page_access_token) return res.status(400).json({ error: 'page_id, name and page_access_token are required' }); await ensureInstagramColumns(); const verified = await axios.get(`https://graph.facebook.com/${GRAPH_VERSION}/${page_id}`, { params: { fields: 'id,username,name', access_token: page_access_token } }); if (String(verified.data?.id) !== String(page_id)) return res.status(400).json({ error: 'Instagram account ID does not match the access token' }); await pgClient.query(`INSERT INTO page_access_token_message (page_id,name,page_access_token,email,user_id,platform,ai,chat_model,cheap_engine,subscription_status) VALUES ($1,$2,$3,$4,$5,'instagram','gemini','gemini-2.0-flash',true,'active') ON CONFLICT (page_id) DO UPDATE SET name=EXCLUDED.name,page_access_token=EXCLUDED.page_access_token,email=EXCLUDED.email,user_id=EXCLUDED.user_id,platform='instagram'`, [String(page_id), verified.data.username || verified.data.name || name, page_access_token, String(req.user.email || '').toLowerCase(), req.user.id]); const result = await pgClient.query(`INSERT INTO fb_message_database (page_id,platform,text_prompt,wait,image_send,image_detection,template) VALUES ($1,'instagram',$2,5,true,true,true) ON CONFLICT (page_id) DO UPDATE SET platform='instagram' RETURNING id`, [String(page_id), 'You are a helpful Instagram sales assistant.']); res.json({ success: true, id: result.rows[0]?.id, db_id: result.rows[0]?.id }); } catch (e) { res.status(400).json({ error: e.response?.data?.error?.message || e.message }); }
});
router.get('/conversations/:accountId', authMiddleware, async (req, res) => { try { const account = await getAccount(req.params.accountId, req.user.id); if (!account) return res.status(404).json({ error: 'Instagram account not found' }); res.json(await getSmartInboxConversations(pgClient, 'instagram', account.page_id)); } catch (e) { res.status(500).json({ error: e.message }); } });
router.get('/messages/:accountId/:senderId', authMiddleware, async (req, res) => { try { const account = await getAccount(req.params.accountId, req.user.id); if (!account) return res.status(404).json({ error: 'Instagram account not found' }); const limit = Math.min(Math.max(parseInt(req.query.limit, 10) || 40, 10), 120); const offset = Math.max(parseInt(req.query.offset, 10) || 0, 0); const { rows } = await pgClient.query(`SELECT CASE WHEN reply_by IN ('bot','admin') THEN 'me' ELSE sender_id END AS from,text AS body,COALESCE(timestamp,EXTRACT(EPOCH FROM created_at)*1000) AS timestamp,reply_by,(reply_by='bot') AS is_ai FROM fb_chats WHERE page_id=$1 AND platform='instagram' AND (sender_id=$2 OR recipient_id=$2) ORDER BY COALESCE(timestamp,EXTRACT(EPOCH FROM created_at)*1000) ASC LIMIT $3 OFFSET $4`, [account.page_id, req.params.senderId, limit, offset]); res.json(rows); } catch (e) { res.status(500).json({ error: e.message }); } });
router.patch('/conversations/:accountId/:senderId/labels', authMiddleware, async (req, res) => { try { const { labelKey, active } = req.body || {}; if (!labelKey || typeof active !== 'boolean') return res.status(400).json({ error: 'labelKey and boolean active are required' }); const account = await getAccount(req.params.accountId, req.user.id); if (!account) return res.status(404).json({ error: 'Instagram account not found' }); res.json({ success: true, conversation: await upsertSmartInboxLabel(pgClient, { platform: 'instagram', resourceId: account.page_id, senderId: req.params.senderId, labelKey, isActive: active }) }); } catch (e) { res.status(500).json({ error: e.message }); } });
router.post('/send', authMiddleware, upload.single('image'), async (req, res) => { try { const account = await getAccount(req.body?.accountId || req.body?.pageId, req.user.id); const to = String(req.body?.to || ''); const message = String(req.body?.message || '').trim(); if (!account || !to || (!message && !req.file)) return res.status(400).json({ error: 'accountId, to and message or image are required' }); const sent = []; if (req.file) { const baseUrl = process.env.PUBLIC_BASE_URL || process.env.BACKEND_URL || `${req.protocol}://${req.get('host')}`; const imageUrl = await imageService.uploadProductImage(req.file.buffer, req.file.mimetype, `smart-inbox/instagram/${account.page_id}`, baseUrl); const response = await facebookService.sendInstagramImage(account.page_id, to, imageUrl, account.page_access_token); const id = response?.message_id || `instagram_admin_image_${Date.now()}`; await dbService.saveFbChat({ page_id: account.page_id, sender_id: account.page_id, recipient_id: to, message_id: id, text: `[Image URL]: ${imageUrl}${message ? `\n${message}` : ''}`, timestamp: Date.now(), status: 'sent', reply_by: 'admin' }); sent.push({ messageId: id, imageUrl }); } if (message) { const response = await facebookService.sendInstagramMessage(account.page_id, to, message, account.page_access_token); const id = response?.message_id || `instagram_admin_${Date.now()}`; await dbService.saveFbChat({ page_id: account.page_id, sender_id: account.page_id, recipient_id: to, message_id: id, text: message, timestamp: Date.now(), status: 'sent', reply_by: 'admin' }); sent.push({ messageId: id, body: message }); } res.json({ success: true, sent }); } catch (e) { res.status(500).json({ error: e.message }); } });
module.exports = router;
