const express = require('express');
const multer = require('multer');
const router = express.Router();
const axios = require('axios');
const pgClient = require('../services/pgClient');
const dbService = require('../services/dbService');
const imageService = require('../services/imageService');
const facebookService = require('../services/facebookService');
const authMiddleware = require('../middleware/authMiddleware');
const instagramController = require('../controllers/instagramController');
const { getSmartInboxConversations, upsertSmartInboxLabel } = require('../utils/smartInbox');
const commentAutomationService = require('../services/commentAutomationService');

const GRAPH_VERSION = process.env.FACEBOOK_GRAPH_VERSION || 'v25.0';
const upload = multer({
    storage: multer.memoryStorage(),
    limits: { fileSize: 16 * 1024 * 1024 },
    fileFilter: (req, file, cb) => cb(null, file.mimetype?.startsWith('image/'))
});

async function ensureInstagramColumns() {
    await pgClient.query(`
        CREATE TABLE IF NOT EXISTS page_access_token_message (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            page_id TEXT UNIQUE NOT NULL,
            name TEXT,
            page_access_token TEXT,
            email TEXT,
            user_id TEXT,
            ai TEXT,
            chat_model TEXT,
            cheap_engine BOOLEAN DEFAULT TRUE,
            subscription_status TEXT DEFAULT 'active'
        );
        CREATE TABLE IF NOT EXISTS fb_message_database (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            page_id TEXT UNIQUE NOT NULL,
            text_prompt TEXT,
            wait INTEGER DEFAULT 5,
            image_send BOOLEAN DEFAULT TRUE,
            image_detection BOOLEAN DEFAULT TRUE,
            template BOOLEAN DEFAULT TRUE,
            reply_message BOOLEAN DEFAULT TRUE,
            order_tracking BOOLEAN DEFAULT TRUE
        );
        CREATE TABLE IF NOT EXISTS fb_chats (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            page_id TEXT,
            sender_id TEXT,
            recipient_id TEXT,
            message_id TEXT UNIQUE,
            text TEXT,
            timestamp BIGINT,
            status TEXT,
            created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
            reply_by TEXT,
            ai_model TEXT
        );
    `);
    await pgClient.query(`ALTER TABLE page_access_token_message ADD COLUMN IF NOT EXISTS platform text NOT NULL DEFAULT 'messenger'`);
    await pgClient.query(`ALTER TABLE page_access_token_message ADD COLUMN IF NOT EXISTS user_id text`);
    await pgClient.query(`ALTER TABLE fb_message_database ADD COLUMN IF NOT EXISTS platform text NOT NULL DEFAULT 'messenger'`);
    await pgClient.query(`ALTER TABLE fb_chats ADD COLUMN IF NOT EXISTS platform text NOT NULL DEFAULT 'messenger'`);
}

const getAccount = async (accountId, userId) => {
    await ensureInstagramColumns();
    const { rows } = await pgClient.query(
        `SELECT p.*, d.id AS db_id
         FROM page_access_token_message p
         LEFT JOIN fb_message_database d ON d.page_id = p.page_id AND d.platform = 'instagram'
         WHERE p.page_id = $1 AND p.platform = 'instagram' AND p.user_id::text = $2
         LIMIT 1`,
        [String(accountId), String(userId)]
    );
    return rows[0] || null;
};

async function saveInstagramAccount({ accountId, name, pageAccessToken, email, userId }) {
    await ensureInstagramColumns();
    await pgClient.query(
        `INSERT INTO page_access_token_message (page_id, name, page_access_token, email, user_id, platform, ai, chat_model, cheap_engine, subscription_status)
         VALUES ($1, $2, $3, $4, $5, 'instagram', 'gemini', 'gemini-2.0-flash', true, 'active')
         ON CONFLICT (page_id) DO UPDATE SET
           name = EXCLUDED.name,
           page_access_token = EXCLUDED.page_access_token,
           email = EXCLUDED.email,
           user_id = EXCLUDED.user_id,
           platform = 'instagram'`,
        [String(accountId), name, pageAccessToken, String(email || '').toLowerCase(), userId]
    );

    const result = await pgClient.query(
        `INSERT INTO fb_message_database (page_id, platform, text_prompt, wait, image_send, image_detection, template, reply_message, order_tracking)
         VALUES ($1, 'instagram', $2, 5, true, true, true, true, true)
         ON CONFLICT (page_id) DO UPDATE SET platform = 'instagram'
         RETURNING id`,
        [String(accountId), 'You are a helpful Instagram sales assistant.']
    );

    return result.rows[0]?.id || null;
}

async function subscribePageForInstagram(pageId, pageAccessToken) {
    const fields = ['messages', 'messaging_postbacks', 'message_deliveries', 'message_reads', 'message_echoes'];
    try {
        await axios.post(`https://graph.facebook.com/${GRAPH_VERSION}/${pageId}/subscribed_apps`, null, {
            params: { access_token: pageAccessToken, subscribed_fields: fields.join(',') },
            timeout: 15000
        });
        return true;
    } catch (error) {
        console.warn(`[Instagram Auto Connect] Page subscription failed for ${pageId}:`, error.response?.data?.error?.message || error.message);
        return false;
    }
}

router.get('/webhook', instagramController.verifyInstagramWebhook);
router.post('/webhook', instagramController.handleInstagramWebhook);

router.get('/pages', authMiddleware, async (req, res) => {
    try {
        await ensureInstagramColumns();
        const { rows } = await pgClient.query(
            `SELECT p.page_id, p.name, p.id, d.id AS db_id
             FROM page_access_token_message p
             LEFT JOIN fb_message_database d ON d.page_id = p.page_id AND d.platform = 'instagram'
             WHERE p.platform = 'instagram' AND p.user_id::text = $1
             ORDER BY p.id DESC`,
            [String(req.user.id)]
        );
        res.json(rows);
    } catch (error) {
        res.status(500).json({ error: error.message });
    }
});

router.post('/pages/auto-connect', authMiddleware, async (req, res) => {
    try {
        const { accessToken } = req.body || {};
        if (!accessToken) return res.status(400).json({ error: 'accessToken is required' });

        const pagesResponse = await axios.get(`https://graph.facebook.com/${GRAPH_VERSION}/me/accounts`, {
            params: {
                fields: 'id,name,access_token,instagram_business_account{id,username,name}',
                access_token: accessToken
            },
            timeout: 20000
        });

        const pages = Array.isArray(pagesResponse.data?.data) ? pagesResponse.data.data : [];
        const connected = [];
        const skipped = [];

        for (const page of pages) {
            const ig = page.instagram_business_account;
            if (!ig?.id || !page.access_token) {
                skipped.push({ page_id: page.id, page_name: page.name, reason: 'No linked Instagram Professional account' });
                continue;
            }

            const dbId = await saveInstagramAccount({
                accountId: ig.id,
                name: ig.username || ig.name || `${page.name} Instagram`,
                pageAccessToken: page.access_token,
                email: req.user.email,
                userId: req.user.id
            });
            const subscribed = await subscribePageForInstagram(page.id, page.access_token);
            connected.push({ page_id: ig.id, name: ig.username || ig.name || `${page.name} Instagram`, db_id: dbId, facebook_page_id: page.id, subscribed });
        }

        res.json({ success: true, connected, skipped });
    } catch (error) {
        res.status(400).json({ error: error.response?.data?.error?.message || error.message });
    }
});

router.post('/pages/manual', authMiddleware, async (req, res) => {
    try {
        const { page_id, name, page_access_token, email } = req.body || {};
        if (!page_id || !name || !page_access_token) return res.status(400).json({ error: 'page_id, name and page_access_token are required' });

        const verified = await axios.get(`https://graph.facebook.com/${GRAPH_VERSION}/${page_id}`, {
            params: { fields: 'id,username,name', access_token: page_access_token },
            timeout: 15000
        });
        if (String(verified.data?.id) !== String(page_id)) return res.status(400).json({ error: 'Instagram account ID does not match the access token' });

        const dbId = await saveInstagramAccount({
            accountId: page_id,
            name: verified.data.username || verified.data.name || name,
            pageAccessToken: page_access_token,
            email: email || req.user.email,
            userId: req.user.id
        });

        res.json({ success: true, id: dbId, db_id: dbId });
    } catch (error) {
        res.status(400).json({ error: error.response?.data?.error?.message || error.message });
    }
});

router.delete('/pages/:accountId', authMiddleware, async (req, res) => {
    try {
        const account = await getAccount(req.params.accountId, req.user.id);
        if (!account) return res.status(404).json({ error: 'Instagram account not found' });
        await pgClient.query(`DELETE FROM fb_message_database WHERE page_id = $1 AND platform = 'instagram'`, [account.page_id]);
        await pgClient.query(`DELETE FROM page_access_token_message WHERE page_id = $1 AND platform = 'instagram'`, [account.page_id]);
        res.json({ success: true });
    } catch (error) {
        res.status(500).json({ error: error.message });
    }
});

router.get('/config/:id', authMiddleware, async (req, res) => {
    try {
        await ensureInstagramColumns();
        const { rows } = await pgClient.query(
            `SELECT d.* FROM fb_message_database d
             JOIN page_access_token_message p ON p.page_id = d.page_id
             WHERE d.id::text = $1 AND d.platform = 'instagram' AND p.platform = 'instagram' AND p.user_id::text = $2 LIMIT 1`,
            [String(req.params.id), String(req.user.id)]
        );
        if (!rows[0]) return res.status(404).json({ error: 'Instagram configuration not found' });
        res.json(rows[0]);
    } catch (error) {
        res.status(500).json({ error: error.message });
    }
});

router.put('/config/:id', authMiddleware, async (req, res) => {
    try {
        const allowed = ['reply_message', 'image_detection', 'image_send', 'order_tracking', 'audio_detection', 'provider', 'api_key', 'chat_model', 'text_prompt', 'wait'];
        const values = Object.entries(req.body || {}).filter(([key]) => allowed.includes(key));
        if (!values.length) return res.json({ success: true });
        const assignments = values.map(([key], index) => `${key === 'provider' ? 'ai' : key} = $${index + 1}`);
        const { rows } = await pgClient.query(
            `UPDATE fb_message_database SET ${assignments.join(', ')} WHERE id::text = $${values.length + 1} AND platform = 'instagram' RETURNING *`,
            [...values.map(([, value]) => value), String(req.params.id)]
        );
        if (!rows[0]) return res.status(404).json({ error: 'Instagram configuration not found' });
        res.json(rows[0]);
    } catch (error) {
        res.status(500).json({ error: error.message });
    }
});

router.get('/conversations/:accountId', authMiddleware, async (req, res) => {
    try {
        const account = await getAccount(req.params.accountId, req.user.id);
        if (!account) return res.status(404).json({ error: 'Instagram account not found' });
        res.json(await getSmartInboxConversations(pgClient, 'instagram', account.page_id));
    } catch (error) {
        res.status(500).json({ error: error.message });
    }
});

router.get('/messages/:accountId/:senderId', authMiddleware, async (req, res) => {
    try {
        const account = await getAccount(req.params.accountId, req.user.id);
        if (!account) return res.status(404).json({ error: 'Instagram account not found' });
        const limit = Math.min(Math.max(parseInt(req.query.limit, 10) || 40, 10), 120);
        const offset = Math.max(parseInt(req.query.offset, 10) || 0, 0);
        const { rows } = await pgClient.query(
            `SELECT CASE WHEN reply_by IN ('bot','admin') THEN 'me' ELSE sender_id END AS from, text AS body,
                    COALESCE(timestamp, EXTRACT(EPOCH FROM created_at) * 1000) AS timestamp, reply_by, (reply_by = 'bot') AS is_ai
             FROM fb_chats
             WHERE page_id = $1 AND platform = 'instagram' AND (sender_id = $2 OR recipient_id = $2)
             ORDER BY COALESCE(timestamp, EXTRACT(EPOCH FROM created_at) * 1000) ASC LIMIT $3 OFFSET $4`,
            [account.page_id, req.params.senderId, limit, offset]
        );
        res.json(rows);
    } catch (error) {
        res.status(500).json({ error: error.message });
    }
});

router.patch('/conversations/:accountId/:senderId/labels', authMiddleware, async (req, res) => {
    try {
        const { labelKey, active } = req.body || {};
        if (!labelKey || typeof active !== 'boolean') return res.status(400).json({ error: 'labelKey and boolean active are required' });
        const account = await getAccount(req.params.accountId, req.user.id);
        if (!account) return res.status(404).json({ error: 'Instagram account not found' });
        res.json({
            success: true,
            conversation: await upsertSmartInboxLabel(pgClient, { platform: 'instagram', resourceId: account.page_id, senderId: req.params.senderId, labelKey, isActive: active })
        });
    } catch (error) {
        res.status(500).json({ error: error.message });
    }
});

router.get('/orders', authMiddleware, async (req, res) => {
    try {
        const account = await getAccount(req.query.account_id, req.user.id);
        if (!account) return res.status(404).json({ error: 'Instagram account not found' });
        const { rows } = await pgClient.query(`SELECT * FROM fb_order_tracking WHERE page_id = $1 ORDER BY created_at DESC`, [account.page_id]);
        res.json(rows);
    } catch (error) {
        res.status(500).json({ error: error.message });
    }
});

router.get('/chats', authMiddleware, async (req, res) => {
    try {
        const account = await getAccount(req.query.account_id, req.user.id);
        if (!account) return res.status(404).json({ error: 'Instagram account not found' });
        const { rows } = await pgClient.query(`SELECT * FROM fb_chats WHERE page_id = $1 AND platform = 'instagram' ORDER BY created_at DESC LIMIT 100`, [account.page_id]);
        res.json(rows);
    } catch (error) {
        res.status(500).json({ error: error.message });
    }
});

router.post('/send', authMiddleware, upload.single('image'), async (req, res) => {
    try {
        const account = await getAccount(req.body?.accountId || req.body?.pageId, req.user.id);
        const to = String(req.body?.to || '');
        const message = String(req.body?.message || '').trim();
        if (!account || !to || (!message && !req.file)) return res.status(400).json({ error: 'accountId, to and message or image are required' });

        const sent = [];
        if (req.file) {
            const baseUrl = process.env.PUBLIC_BASE_URL || process.env.BACKEND_URL || `${req.protocol}://${req.get('host')}`;
            const imageUrl = await imageService.uploadProductImage(req.file.buffer, req.file.mimetype, `smart-inbox/instagram/${account.page_id}`, baseUrl);
            const response = await facebookService.sendInstagramImage(account.page_id, to, imageUrl, account.page_access_token);
            const id = response?.message_id || `instagram_admin_image_${Date.now()}`;
            await dbService.saveFbChat({ page_id: account.page_id, sender_id: account.page_id, recipient_id: to, message_id: id, text: `[Image URL]: ${imageUrl}${message ? `\n${message}` : ''}`, timestamp: Date.now(), status: 'sent', reply_by: 'admin', platform: 'instagram' });
            sent.push({ messageId: id, imageUrl });
        }
        if (message) {
            const response = await facebookService.sendInstagramMessage(account.page_id, to, message, account.page_access_token);
            const id = response?.message_id || `instagram_admin_${Date.now()}`;
            await dbService.saveFbChat({ page_id: account.page_id, sender_id: account.page_id, recipient_id: to, message_id: id, text: message, timestamp: Date.now(), status: 'sent', reply_by: 'admin', platform: 'instagram' });
            sent.push({ messageId: id, body: message });
        }
        res.json({ success: true, sent });
    } catch (error) {
        res.status(500).json({ error: error.message });
    }
});

router.get('/comment-automation/:accountId', authMiddleware, async (req, res) => {
    try {
        const account = await getAccount(req.params.accountId, req.user.id);
        if (!account) return res.status(404).json({ error: 'Instagram account not found' });
        res.json(await commentAutomationService.getConfig('instagram', account.page_id));
    } catch (error) { res.status(500).json({ error: error.message }); }
});

router.put('/comment-automation/:accountId', authMiddleware, async (req, res) => {
    try {
        const account = await getAccount(req.params.accountId, req.user.id);
        if (!account) return res.status(404).json({ error: 'Instagram account not found' });
        res.json(await commentAutomationService.updateConfig('instagram', account.page_id, req.body));
    } catch (error) { res.status(500).json({ error: error.message }); }
});

router.get('/post-mappings/:accountId', authMiddleware, async (req, res) => {
    try {
        const account = await getAccount(req.params.accountId, req.user.id);
        if (!account) return res.status(404).json({ error: 'Instagram account not found' });
        res.json(await commentAutomationService.listMappings('instagram', account.page_id));
    } catch (error) { res.status(500).json({ error: error.message }); }
});

router.post('/post-mappings/:accountId', authMiddleware, async (req, res) => {
    try {
        const account = await getAccount(req.params.accountId, req.user.id);
        if (!account) return res.status(404).json({ error: 'Instagram account not found' });
        res.json(await commentAutomationService.upsertMapping('instagram', account.page_id, req.body));
    } catch (error) { res.status(500).json({ error: error.message }); }
});

module.exports = router;
