const express = require('express');
const multer = require('multer');
const router = express.Router();
const pgClient = require('../services/pgClient');
const dbService = require('../services/dbService');
const imageService = require('../services/imageService');
const instagramService = require('../services/instagramService');
const authMiddleware = require('../middleware/authMiddleware');
const instagramController = require('../controllers/instagramController');
const { getSmartInboxConversations, upsertSmartInboxLabel } = require('../utils/smartInbox');
const commentAutomationService = require('../services/commentAutomationService');

const upload = multer({
    storage: multer.memoryStorage(),
    limits: { fileSize: 16 * 1024 * 1024 },
    fileFilter: (req, file, cb) => cb(null, file.mimetype?.startsWith('image/'))
});

async function ensureInstagramTables() {
    await pgClient.query(`
        CREATE TABLE IF NOT EXISTS instagram_accounts (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            instagram_account_id TEXT NOT NULL,
            instagram_username TEXT,
            name TEXT,
            facebook_page_id TEXT,
            page_access_token TEXT,
            user_access_token TEXT,
            email TEXT,
            user_id TEXT,
            ai TEXT DEFAULT 'gemini',
            chat_model TEXT DEFAULT 'gemini-2.0-flash',
            cheap_engine BOOLEAN DEFAULT TRUE,
            subscription_status TEXT DEFAULT 'active',
            created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
            updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
            UNIQUE(user_id, instagram_account_id)
        );

        CREATE TABLE IF NOT EXISTS instagram_message_database (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            instagram_account_id TEXT NOT NULL UNIQUE,
            user_id TEXT,
            text_prompt TEXT,
            wait INTEGER DEFAULT 5,
            image_send BOOLEAN DEFAULT TRUE,
            image_detection BOOLEAN DEFAULT TRUE,
            template BOOLEAN DEFAULT TRUE,
            reply_message BOOLEAN DEFAULT TRUE,
            order_tracking BOOLEAN DEFAULT TRUE,
            swipe_reply BOOLEAN DEFAULT FALSE,
            audio_detection BOOLEAN DEFAULT FALSE,
            block_emoji TEXT DEFAULT '',
            unblock_emoji TEXT DEFAULT '',
            image_prompt TEXT DEFAULT '',
            check_conversion INTEGER DEFAULT 20,
            temperature NUMERIC DEFAULT 0.7,
            top_p NUMERIC DEFAULT 0.9,
            ai TEXT,
            api_key TEXT,
            chat_model TEXT,
            created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
            updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
        );

        CREATE TABLE IF NOT EXISTS instagram_chats (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            instagram_account_id TEXT,
            sender_id TEXT,
            recipient_id TEXT,
            message_id TEXT UNIQUE,
            text TEXT,
            timestamp BIGINT,
            status TEXT DEFAULT 'pending',
            created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
            reply_by TEXT,
            token INTEGER DEFAULT 0,
            ai_model TEXT,
            sender_name TEXT
        );

        CREATE TABLE IF NOT EXISTS instagram_order_tracking (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            instagram_account_id TEXT,
            sender_id TEXT,
            status TEXT,
            created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
            updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
        );

        CREATE INDEX IF NOT EXISTS idx_instagram_accounts_user ON instagram_accounts(user_id);
        CREATE INDEX IF NOT EXISTS idx_instagram_chats_account_sender ON instagram_chats(instagram_account_id, sender_id);
        CREATE INDEX IF NOT EXISTS idx_instagram_orders_account_sender ON instagram_order_tracking(instagram_account_id, sender_id);
    `);
}

function mapAccount(row) {
    if (!row) return null;
    return {
        ...row,
        page_id: row.instagram_account_id,
        db_id: row.db_id,
        page_access_token: row.page_access_token
    };
}

async function migrateLegacyInstagramRows(userId) {
    const { rows } = await pgClient.query(
        `SELECT p.page_id, p.name, p.page_access_token, p.email, p.user_id, p.ai, p.chat_model, p.cheap_engine, p.subscription_status,
                d.id AS old_db_id, d.text_prompt, d.wait, d.image_send, d.image_detection, d.template, d.reply_message, d.order_tracking,
                d.swipe_reply, d.audio_detection, d.block_emoji, d.unblock_emoji, d.image_prompt, d.check_conversion, d.temperature, d.top_p
         FROM page_access_token_message p
         LEFT JOIN fb_message_database d ON d.page_id = p.page_id AND d.platform = 'instagram'
         WHERE p.platform = 'instagram' AND p.user_id::text = $1`,
        [String(userId)]
    ).catch(() => ({ rows: [] }));

    for (const row of rows) {
        await saveInstagramAccount({
            accountId: row.page_id,
            username: row.name,
            name: row.name,
            pageAccessToken: row.page_access_token,
            userAccessToken: null,
            facebookPageId: null,
            email: row.email,
            userId: row.user_id,
            config: row
        });
    }
}

async function getAccount(accountId, userId) {
    await ensureInstagramTables();
    const { rows } = await pgClient.query(
        `SELECT a.*, d.id AS db_id
         FROM instagram_accounts a
         LEFT JOIN instagram_message_database d ON d.instagram_account_id = a.instagram_account_id
         WHERE a.instagram_account_id = $1 AND a.user_id::text = $2
         LIMIT 1`,
        [String(accountId), String(userId)]
    );
    return mapAccount(rows[0]);
}

async function saveInstagramAccount({ accountId, username, name, pageAccessToken, userAccessToken, facebookPageId, email, userId, config = {} }) {
    await ensureInstagramTables();
    await pgClient.query(
        `INSERT INTO instagram_accounts
            (instagram_account_id, instagram_username, name, facebook_page_id, page_access_token, user_access_token, email, user_id, ai, chat_model, cheap_engine, subscription_status)
         VALUES ($1, $2, $3, $4, $5, $6, $7, $8, COALESCE($9, 'gemini'), COALESCE($10, 'gemini-2.0-flash'), COALESCE($11, TRUE), COALESCE($12, 'active'))
         ON CONFLICT (user_id, instagram_account_id) DO UPDATE SET
            instagram_username = EXCLUDED.instagram_username,
            name = EXCLUDED.name,
            facebook_page_id = EXCLUDED.facebook_page_id,
            page_access_token = EXCLUDED.page_access_token,
            user_access_token = COALESCE(EXCLUDED.user_access_token, instagram_accounts.user_access_token),
            email = EXCLUDED.email,
            ai = COALESCE(instagram_accounts.ai, EXCLUDED.ai),
            chat_model = COALESCE(instagram_accounts.chat_model, EXCLUDED.chat_model),
            cheap_engine = COALESCE(instagram_accounts.cheap_engine, EXCLUDED.cheap_engine),
            subscription_status = COALESCE(instagram_accounts.subscription_status, EXCLUDED.subscription_status),
            updated_at = NOW()`,
        [
            String(accountId),
            username || null,
            name || username || `Instagram ${accountId}`,
            facebookPageId ? String(facebookPageId) : null,
            pageAccessToken,
            userAccessToken || null,
            String(email || '').toLowerCase(),
            String(userId),
            config.ai,
            config.chat_model,
            config.cheap_engine,
            config.subscription_status
        ]
    );

    const result = await pgClient.query(
        `INSERT INTO instagram_message_database
            (instagram_account_id, user_id, text_prompt, wait, image_send, image_detection, template, reply_message, order_tracking,
             swipe_reply, audio_detection, block_emoji, unblock_emoji, image_prompt, check_conversion, temperature, top_p, ai, chat_model)
         VALUES ($1, $2, $3, COALESCE($4, 5), COALESCE($5, TRUE), COALESCE($6, TRUE), COALESCE($7, TRUE), COALESCE($8, TRUE), COALESCE($9, TRUE),
             COALESCE($10, FALSE), COALESCE($11, FALSE), COALESCE($12, ''), COALESCE($13, ''), COALESCE($14, ''), COALESCE($15, 20), COALESCE($16, 0.7), COALESCE($17, 0.9), $18, $19)
         ON CONFLICT (instagram_account_id) DO UPDATE SET
            user_id = EXCLUDED.user_id,
            updated_at = NOW()
         RETURNING id`,
        [
            String(accountId),
            String(userId),
            config.text_prompt || 'You are a helpful Instagram sales assistant.',
            config.wait,
            config.image_send,
            config.image_detection,
            config.template,
            config.reply_message,
            config.order_tracking,
            config.swipe_reply,
            config.audio_detection,
            config.block_emoji,
            config.unblock_emoji,
            config.image_prompt,
            config.check_conversion,
            config.temperature,
            config.top_p,
            config.ai,
            config.chat_model
        ]
    );

    return result.rows[0]?.id || null;
}

router.get('/webhook', instagramController.verifyInstagramWebhook);
router.post('/webhook', instagramController.handleInstagramWebhook);
router.get('/webhook/monitor', authMiddleware, instagramController.getInstagramWebhookLogs);

router.get('/pages', authMiddleware, async (req, res) => {
    try {
        await ensureInstagramTables();
        let result = await pgClient.query(
            `SELECT a.instagram_account_id AS page_id, a.instagram_account_id, a.instagram_username, a.name, a.facebook_page_id, d.id AS db_id
             FROM instagram_accounts a
             LEFT JOIN instagram_message_database d ON d.instagram_account_id = a.instagram_account_id
             WHERE a.user_id::text = $1
             ORDER BY a.instagram_account_id DESC`,
            [String(req.user.id)]
        );

        if (result.rows.length === 0) {
            await migrateLegacyInstagramRows(req.user.id);
            result = await pgClient.query(
                `SELECT a.instagram_account_id AS page_id, a.instagram_account_id, a.instagram_username, a.name, a.facebook_page_id, d.id AS db_id
                 FROM instagram_accounts a
                 LEFT JOIN instagram_message_database d ON d.instagram_account_id = a.instagram_account_id
                 WHERE a.user_id::text = $1
                 ORDER BY a.instagram_account_id DESC`,
                [String(req.user.id)]
            );
        }

        res.json(result.rows);
    } catch (error) {
        res.status(500).json({ error: error.message });
    }
});

router.post('/pages/auto-connect', authMiddleware, async (req, res) => {
    try {
        const { accessToken } = req.body || {};
        if (!accessToken) return res.status(400).json({ error: 'accessToken is required' });

        const pages = await instagramService.fetchLinkedInstagramAccounts(accessToken);
        const connected = [];
        const skipped = [];

        for (const page of pages) {
            const ig = page.instagram_business_account;
            if (!ig?.id || !page.access_token) {
                skipped.push({ page_id: page.id, page_name: page.name, reason: 'No linked Instagram Professional account' });
                continue;
            }

            const dbId = await saveInstagramAccount({
                accountId: ig.id,
                username: ig.username,
                name: ig.username || ig.name || `${page.name} Instagram`,
                pageAccessToken: page.access_token,
                userAccessToken: accessToken,
                facebookPageId: page.id,
                email: req.user.email,
                userId: req.user.id
            });
            const subscribed = await instagramService.subscribeLinkedPage(page.id, page.access_token);
            connected.push({
                page_id: ig.id,
                instagram_account_id: ig.id,
                instagram_username: ig.username || null,
                name: ig.username || ig.name || `${page.name} Instagram`,
                db_id: dbId,
                facebook_page_id: page.id,
                subscribed
            });
        }

        res.json({ success: true, connected, skipped });
    } catch (error) {
        res.status(400).json({ error: error.response?.data?.error?.message || error.message });
    }
});

router.post('/pages/manual', authMiddleware, async (req, res) => {
    try {
        const { page_id, name, page_access_token, email, facebook_page_id } = req.body || {};
        if (!page_id || !name || !page_access_token) return res.status(400).json({ error: 'page_id, name and page_access_token are required' });

        const verified = await instagramService.verifyInstagramAccount(page_id, page_access_token);
        const dbId = await saveInstagramAccount({
            accountId: page_id,
            username: verified.username,
            name: verified.username || verified.name || name,
            pageAccessToken: page_access_token,
            userAccessToken: null,
            facebookPageId: facebook_page_id || null,
            email: email || req.user.email,
            userId: req.user.id
        });

        res.json({ success: true, id: dbId, db_id: dbId });
    } catch (error) {
        res.status(400).json({ error: error.response?.data?.error?.message || error.message });
    }
});

router.delete('/pages/:accountId', authMiddleware, async (req, res) => {
    try {
        const account = await getAccount(req.params.accountId, req.user.id);
        if (!account) return res.status(404).json({ error: 'Instagram account not found' });
        await pgClient.query(`DELETE FROM instagram_message_database WHERE instagram_account_id = $1`, [account.page_id]);
        await pgClient.query(`DELETE FROM instagram_accounts WHERE instagram_account_id = $1 AND user_id::text = $2`, [account.page_id, String(req.user.id)]);
        res.json({ success: true });
    } catch (error) {
        res.status(500).json({ error: error.message });
    }
});

router.get('/config/:id', authMiddleware, async (req, res) => {
    try {
        await ensureInstagramTables();
        const { rows } = await pgClient.query(
            `SELECT d.*, a.ai, a.chat_model, a.cheap_engine, a.page_access_token
             FROM instagram_message_database d
             JOIN instagram_accounts a ON a.instagram_account_id = d.instagram_account_id
             WHERE d.id::text = $1 AND a.user_id::text = $2
             LIMIT 1`,
            [String(req.params.id), String(req.user.id)]
        );
        if (!rows[0]) return res.status(404).json({ error: 'Instagram configuration not found' });
        res.json(rows[0]);
    } catch (error) {
        res.status(500).json({ error: error.message });
    }
});

router.put('/config/:id', authMiddleware, async (req, res) => {
    try {
        await ensureInstagramTables();
        const allowed = ['reply_message', 'image_detection', 'image_send', 'order_tracking', 'audio_detection', 'swipe_reply', 'template', 'block_emoji', 'unblock_emoji', 'image_prompt', 'check_conversion', 'temperature', 'top_p', 'provider', 'api_key', 'chat_model', 'text_prompt', 'wait'];
        const values = Object.entries(req.body || {}).filter(([key]) => allowed.includes(key));
        if (!values.length) return res.json({ success: true });
        const assignments = values.map(([key], index) => `${key === 'provider' ? 'ai' : key} = $${index + 1}`);
        const { rows } = await pgClient.query(
            `UPDATE instagram_message_database d SET ${assignments.join(', ')}, updated_at = NOW()
             FROM instagram_accounts a
             WHERE d.id::text = $${values.length + 1}
               AND a.instagram_account_id = d.instagram_account_id
               AND a.user_id::text = $${values.length + 2}
             RETURNING d.*`,
            [...values.map(([, value]) => value), String(req.params.id), String(req.user.id)]
        );
        if (!rows[0]) return res.status(404).json({ error: 'Instagram configuration not found' });
        res.json(rows[0]);
    } catch (error) {
        res.status(500).json({ error: error.message });
    }
});

router.get('/conversations/:accountId', authMiddleware, async (req, res) => {
    try {
        const account = await getAccount(req.params.accountId, req.user.id);
        if (!account) return res.status(404).json({ error: 'Instagram account not found' });
        res.json(await getSmartInboxConversations(pgClient, 'instagram', account.page_id));
    } catch (error) {
        res.status(500).json({ error: error.message });
    }
});

router.get('/messages/:accountId/:senderId', authMiddleware, async (req, res) => {
    try {
        const account = await getAccount(req.params.accountId, req.user.id);
        if (!account) return res.status(404).json({ error: 'Instagram account not found' });
        const limit = Math.min(Math.max(parseInt(req.query.limit, 10) || 40, 10), 120);
        const offset = Math.max(parseInt(req.query.offset, 10) || 0, 0);
        const { rows } = await pgClient.query(
            `SELECT * FROM (
                SELECT id, message_id, CASE WHEN reply_by IN ('bot','admin') THEN 'me' ELSE sender_id END AS from, text AS body,
                       COALESCE(timestamp, EXTRACT(EPOCH FROM created_at) * 1000) AS timestamp, reply_by, (reply_by = 'bot') AS is_ai
                FROM instagram_chats
                WHERE instagram_account_id = $1 AND (sender_id = $2 OR recipient_id = $2)
                ORDER BY COALESCE(timestamp, EXTRACT(EPOCH FROM created_at) * 1000) DESC LIMIT $3 OFFSET $4
             ) recent_messages
             ORDER BY timestamp ASC`,
            [account.page_id, req.params.senderId, limit, offset]
        );
        res.json(rows);
    } catch (error) {
        res.status(500).json({ error: error.message });
    }
});

router.patch('/conversations/:accountId/:senderId/labels', authMiddleware, async (req, res) => {
    try {
        const { labelKey, active } = req.body || {};
        if (!labelKey || typeof active !== 'boolean') return res.status(400).json({ error: 'labelKey and boolean active are required' });
        const account = await getAccount(req.params.accountId, req.user.id);
        if (!account) return res.status(404).json({ error: 'Instagram account not found' });
        res.json({
            success: true,
            conversation: await upsertSmartInboxLabel(pgClient, { platform: 'instagram', resourceId: account.page_id, senderId: req.params.senderId, labelKey, isActive: active })
        });
    } catch (error) {
        res.status(500).json({ error: error.message });
    }
});

router.get('/orders', authMiddleware, async (req, res) => {
    try {
        const account = await getAccount(req.query.account_id, req.user.id);
        if (!account) return res.status(404).json({ error: 'Instagram account not found' });
        const { rows } = await pgClient.query(`SELECT * FROM instagram_order_tracking WHERE instagram_account_id = $1 ORDER BY created_at DESC`, [account.page_id]);
        res.json(rows);
    } catch (error) {
        res.status(500).json({ error: error.message });
    }
});

router.get('/chats', authMiddleware, async (req, res) => {
    try {
        const account = await getAccount(req.query.account_id, req.user.id);
        if (!account) return res.status(404).json({ error: 'Instagram account not found' });
        const { rows } = await pgClient.query(`SELECT *, instagram_account_id AS page_id, 'instagram' AS platform FROM instagram_chats WHERE instagram_account_id = $1 ORDER BY created_at DESC LIMIT 100`, [account.page_id]);
        res.json(rows);
    } catch (error) {
        res.status(500).json({ error: error.message });
    }
});

router.post('/send', authMiddleware, upload.single('image'), async (req, res) => {
    try {
        const account = await getAccount(req.body?.accountId || req.body?.pageId, req.user.id);
        const to = String(req.body?.to || '');
        const message = String(req.body?.message || '').trim();
        if (!account || !to || (!message && !req.file)) return res.status(400).json({ error: 'accountId, to and message or image are required' });

        const sent = [];
        if (req.file) {
            const baseUrl = process.env.PUBLIC_BASE_URL || process.env.BACKEND_URL || `${req.protocol}://${req.get('host')}`;
            const imageUrl = await imageService.uploadProductImage(req.file.buffer, req.file.mimetype, `smart-inbox/instagram/${account.page_id}`, baseUrl);
            const response = await instagramService.sendImage(account.page_id, to, imageUrl, account.page_access_token);
            const id = response?.message_id || `instagram_admin_image_${Date.now()}`;
            await dbService.saveInstagramChat({ instagram_account_id: account.page_id, sender_id: account.page_id, recipient_id: to, message_id: id, text: `[Image URL]: ${imageUrl}${message ? `\n${message}` : ''}`, timestamp: Date.now(), status: 'sent', reply_by: 'admin' });
            sent.push({ messageId: id, imageUrl });
        }
        if (message) {
            const response = await instagramService.sendMessage(account.page_id, to, message, account.page_access_token);
            const id = response?.message_id || `instagram_admin_${Date.now()}`;
            await dbService.saveInstagramChat({ instagram_account_id: account.page_id, sender_id: account.page_id, recipient_id: to, message_id: id, text: message, timestamp: Date.now(), status: 'sent', reply_by: 'admin' });
            sent.push({ messageId: id, body: message });
        }
        res.json({
            success: true,
            message: {
                message_id: sent[0]?.messageId || null,
                from: 'me',
                body: sent.map((part) => part.body).filter(Boolean).join('\n\n'),
                timestamp: Date.now(),
                reply_by: 'admin',
                is_ai: false
            },
            sent
        });
    } catch (error) {
        res.status(500).json({ error: error.message });
    }
});

router.get('/comment-automation/:accountId', authMiddleware, async (req, res) => {
    try {
        const account = await getAccount(req.params.accountId, req.user.id);
        if (!account) return res.status(404).json({ error: 'Instagram account not found' });
        res.json(await commentAutomationService.getConfig('instagram', account.page_id));
    } catch (error) { res.status(500).json({ error: error.message }); }
});

router.put('/comment-automation/:accountId', authMiddleware, async (req, res) => {
    try {
        const account = await getAccount(req.params.accountId, req.user.id);
        if (!account) return res.status(404).json({ error: 'Instagram account not found' });
        res.json(await commentAutomationService.updateConfig('instagram', account.page_id, req.body));
    } catch (error) { res.status(500).json({ error: error.message }); }
});

router.get('/post-mappings/:accountId', authMiddleware, async (req, res) => {
    try {
        const account = await getAccount(req.params.accountId, req.user.id);
        if (!account) return res.status(404).json({ error: 'Instagram account not found' });
        res.json(await commentAutomationService.listMappings('instagram', account.page_id));
    } catch (error) { res.status(500).json({ error: error.message }); }
});

router.post('/post-mappings/:accountId', authMiddleware, async (req, res) => {
    try {
        const account = await getAccount(req.params.accountId, req.user.id);
        if (!account) return res.status(404).json({ error: 'Instagram account not found' });
        res.json(await commentAutomationService.upsertMapping('instagram', account.page_id, req.body));
    } catch (error) { res.status(500).json({ error: error.message }); }
});

module.exports = router;
