CREATE TABLE IF NOT EXISTS business_profiles (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID,
    owner_email TEXT NOT NULL,
    name TEXT NOT NULL,
    business_type TEXT NOT NULL CHECK (business_type IN ('ecommerce', 'digital_service', 'appointment')),
    description TEXT,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS business_profile_resources (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    business_profile_id BIGINT NOT NULL REFERENCES business_profiles(id) ON DELETE CASCADE,
    platform TEXT NOT NULL CHECK (platform IN ('messenger', 'whatsapp', 'instagram')),
    resource_id TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    UNIQUE (business_profile_id, platform, resource_id)
);

CREATE INDEX IF NOT EXISTS idx_business_profiles_owner_email ON business_profiles(LOWER(owner_email));
CREATE INDEX IF NOT EXISTS idx_business_profile_resources_lookup ON business_profile_resources(platform, resource_id);
CREATE INDEX IF NOT EXISTS idx_business_profile_resources_profile ON business_profile_resources(business_profile_id);

ALTER TABLE fb_order_tracking ADD COLUMN IF NOT EXISTS business_profile_id BIGINT;
ALTER TABLE fb_order_tracking ADD COLUMN IF NOT EXISTS business_type TEXT;
ALTER TABLE fb_order_tracking ADD COLUMN IF NOT EXISTS order_mode TEXT;

ALTER TABLE whatsapp_order_tracking ADD COLUMN IF NOT EXISTS business_profile_id BIGINT;
ALTER TABLE whatsapp_order_tracking ADD COLUMN IF NOT EXISTS business_type TEXT;
ALTER TABLE whatsapp_order_tracking ADD COLUMN IF NOT EXISTS order_mode TEXT;

ALTER TABLE instagram_order_tracking ADD COLUMN IF NOT EXISTS business_profile_id BIGINT;
ALTER TABLE instagram_order_tracking ADD COLUMN IF NOT EXISTS business_type TEXT;
ALTER TABLE instagram_order_tracking ADD COLUMN IF NOT EXISTS order_mode TEXT;
